### PR TITLE
Convert README to Markdown

### PR DESCRIPTION
**Pull request by pquentin**
The main impetus for this was to remove the reST parsing in setup.py, which is an important step towards #2538.

I've also used this as an opportunity to use our real dark mode logo, by abusing the fact that https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/ was implemented with CSS. (This could have been done in reST too, but I only found out when working on this change.)

This also removes the Tidelift logo as I didn't try using a Markdown table.

:warning: We need to upload a packaged version of this to test.pypi.org to make sure it renders correctly there.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
There's a much easier to support reproducible builds without using markdown. You could have started specifying things in setup.cfg the way others do with `file:README.rst` and removed it from here. That's an even bigger step towards static metadata

**Comment by sethmlarson** [comment]
@sigmavirus24 We'll definitely be doing the `readme:README` config. Our issue is rST doesn't allow embedding HTML unlike markdown so our `setup.py` had logic which stripped the HTML out of rST before building the package.

**Comment by shazow** [comment]
What issues does markdpwn introduce for reproducible builds?

**Comment by pquentin** [comment]
> Our issue is rST doesn't allow embedding HTML unlike markdown 

It's supported in GitHub, but not in PyPI, which is why we stripped that in setup.py.

> What issues does markdown introduce for reproducible builds?

Why are you asking that? Markdown does not introduce issues, hence the switch.

**Comment by shazow** [comment]
@pquentin Er that was a question for @sigmavirus24's statement about

> There's a much easier to support reproducible builds without using markdown. [...]

**Comment by sigmavirus24** [comment]
> @pquentin Er that was a question for @sigmavirus24's statement about
> 
> > There's a much easier to support reproducible builds without using markdown. [...]

Was trying to say "without switching to markdown" markdown poses no issues

**Comment by pquentin** [comment]
I had to restore the logo with white outlines because PyPI does not support `gh-dark-mode-only` / `gh-light-mode-only`. I found a hack with a markdown image inside a `<h1>` tag that works:

 * GitHub: https://github.com/pquentin/urllib3/tree/markdown-readme
 * PyPI: https://test.pypi.org/project/urllib3-markdown-pquentin/2.0.0.dev0/

**Review by sethmlarson — APPROVED** [review]
Looks great, that's awesome that we can have our banner image on PyPI finally! :tada: Thanks @pquentin

**Pull request merged**
