### PR TITLE
style(__init__): Added typing for StreamHandler

### PR DESCRIPTION
**Pull request by SaidBySolo**
This pr makes my linter less complaining.

### CODE REVIEW

**Comment by SaidBySolo** [comment]
Not backward compatible

**Comment by pquentin** [comment]
What do you mean, "not backward compatible"?

**Comment by SaidBySolo** [comment]
> What do you mean, "not backward compatible"?
The ``SteamHandler[TextIO]`` syntax does not work in version 3.8.

**Comment by pquentin** [comment]
I see, thanks. No, unfortunately we support Python 3.6+

**Pull request closed without merging**
