### PR TITLE
Pin all workflows to commit shas

### PR DESCRIPTION
**Pull request by sethmlarson**
Part of the OpenSSF scorecard for pinning dependencies is pinning all GitHub Actions to commit SHAs.

```
$ scorecard-linux-amd64 --local urllib3 --checks Pinned-Dependencies

Starting [Pinned-Dependencies]
Finished [Pinned-Dependencies]

RESULTS
-------
Aggregate score: 10.0 / 10

Check scores:
|---------|---------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------|
|  SCORE  |        NAME         |           REASON            |                                             DOCUMENTATION/REMEDIATION                                              |
|---------|---------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------|
| 10 / 10 | Pinned-Dependencies | all dependencies are pinned | https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/docs/checks.md#pinned-dependencies |
|---------|---------------------|-----------------------------|--------------------------------------------------------------------------------------------------------------------|
```

### CODE REVIEW

**Review by pquentin — COMMENTED** [review]
Thanks, the pin themselves look good. Why did we have to remove the names though? The resulting logs are harder to read:

image

**Comment by sethmlarson** [comment]
@pquentin Hmm! I thought that the actions would use some sort of default name that would keep them readable. I'll add back the names.

**Comment by sethmlarson** [comment]
I quoted all the names and I liked having the conditional always on top so I moved the `if` section to the top of each job step. This makes me want there to be a GitHub Action auto-formatter like Black.

**Review by illia-v — APPROVED** [review]

**Review by pquentin — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
