### PR TITLE
Add check for correct h2 version range

### LINKED ISSUE #3290: Add check for correct h2 version range
Similar to our other third-party package support, we should be checking which version of h2 is installed and raise an error in the case we get an unsupported version. We know that h2 uses semver, so we can check the major version is in our desired range.

### PR DESCRIPTION
**Pull request by ktpa**
Tested according to [contribution guidelines](https://urllib3.readthedocs.io/en/stable/contributing.html).

Closes #3290.

### CODE REVIEW

**Comment by ktpa** [comment]
@sethmlarson friendly nudge

**Comment by ktpa** [comment]
@sethmlarson @illia-v @shazow nudge^3

**Review by sethmlarson — DISMISSED** [review]
Thanks Quentin for getting this one in good shape!

**Review by sethmlarson — APPROVED** [review]
LGTM

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
