### PR TITLE
Run pull request builds on GitHub Actions

### PR DESCRIPTION
**Pull request by sethmlarson**
Can't merge this one because we lose the integration/release builds but want to try out GHA

### CODE REVIEW

**Comment by pquentin** [comment]
Note that switching to travis-ci.com will require us to change the checks in the repo GitHub settings

**Comment by sethmlarson** [comment]
@pquentin Do you mean "switching to GitHub Actions" instead of travis-ci.com?

**Comment by pquentin** [comment]
No I did mean travis-ci.com, I had to change the required checks for Trio

**Comment by pquentin** [comment]
Okay so I pushed the branch `github-actions-ubuntu` to urllib3, can't delete anymore but it confuses the build checks

**Comment by pquentin** [comment]
This is ready to be undrafted and merged! No more Travis CI for pull requests

**Comment by sethmlarson** [comment]
Merging! :rocket:

**Pull request merged**
