### PR TITLE
Advance-usage.rst: Adds missing import for codecs section

### PR DESCRIPTION
**Pull request by Pradhvan**
Advance-usage.rst: Adds missing import for codecs section
* Adds missing import for json, urllib3
* Adds print statement for better formating

### CODE REVIEW

**Comment by Pradhvan** [comment]
@pquentin I create branch from `1.26.x` on my fork in the local but not sure why it's showing 3 commits instead of the just one that is the change. 

Can you please point me in the right direction if I this isn't the right way to do it ? 😄

**Review by pquentin — CHANGES_REQUESTED** [review]
Thanks! Yeah your pull request is not based on our current 1.26.x branch, but don't worry about it, we will squash the commits when merging. The important part is that the "Files changed" tab on GitHub shows what you'd expect.

So this particular change looks good, but there are more places where some snippets are missing imports. (Even the `main` branch does not get this fully right.) Can you please fix them too?

**Comment by Pradhvan** [comment]
@pquentin sure, I can take a look at other snippets in the `1.26.x` and add the changes in the same PR. 

If you want the same for the `main` branch I can create a separate PR once I am done with this. 😄

**Comment by sethmlarson** [comment]
@Pradhvan Are you still planning to update this PR?

**Comment by sethmlarson** [comment]
No problem, I'm in the same boat as well. Take your time if you need to!

**Comment by sethmlarson** [comment]
Going to close this as it's lost steam.

**Pull request closed without merging**
