### PR TITLE
simplify conditional block

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by SethMichaelLarson** [comment]
Thanks for this! The CI failure is coming from PyOpenSSL dropping support for 18.0.0 which I'm fixing in #1389. Once that lands we can sync this PR and get this merged. :)

**Comment by ofek** [comment]
Cool, just ping me when that's merged. Thank you!

**Comment by ofek** [comment]
Thanks!

**Comment by SethMichaelLarson** [comment]
Thanks for this! :tada: Hope you'll stick around and tackle other issues if you have time. :)

**Pull request merged**
