### PR TITLE
[1.26] Revise CI config and fix tests for CPython 3.12 & 3.13

### PR DESCRIPTION
**Pull request by illia-v**
I spent some time investigating why our 1.26 tests hanged with CPython 3.12, and found out that a fix related to `ssl` module changes was not backported to the branch. This has been causing silent failures in threads which led to CI timeouts.

In this PR, I'm backporting needed changes, enabling CI for CPython 3.12 and 3.13, and making some optimizations to get the tests pass without timeouts.

As in main, `test_requesting_large_resources_via_ssl` runs in a separate CI job, but I chose a different approach to #3181 to avoid asking redistributors to change their flows.

### CODE REVIEW

**Comment by illia-v** [comment]
I'll need to check why [macOS 3.11](https://github.com/urllib3/urllib3/actions/runs/10214710465/job/28262646938?pr=3436#logs) hangs, the same happens in my fork

**Comment by pquentin** [comment]
The macOS tests hangs on `test/test_wait.py::test_eintr_zero_timeout[wait_for_socket]`. I don't consider this blocking for this specific pull request.

**Review by pquentin — DISMISSED** [review]
Thanks @illia-v! LGTM.

**Comment by illia-v** [comment]
> The macOS tests hangs on `test/test_wait.py::test_eintr_zero_timeout[wait_for_socket]`. I don't consider this blocking for this specific pull request. We do need a timeout though so that it does not hang forever.

I found a fix for the timeout in 70b851b73e42dd5fdfbce3aba79be26846c9edc1 and it uncovered [a coverage issue](https://github.com/urllib3/urllib3/actions/runs/10215846236/job/28267260706), so I had to fix it too by backporting a part of [your commit](https://github.com/illia-v/urllib3/commit/5d93c9c6c01efc469200044027c21c6e661f2a99)

**Review by pquentin — APPROVED** [review]
Excellent work! LGTM.

**Review by sethmlarson — APPROVED** [review]
This is awesome, thank you so much @illia-v! :pray:

**Pull request merged**
