### PR TITLE
Deprecate negotiating TLSv1 and TLSv1.1 by default

### LINKED ISSUE #1990: [v1.26] Deprecate TLS <1.2 on v1.26.x
If we detect "TLSv1" or "TLSv1.1" from any `SSLSocket.version()` we should be emitting a `DeprecationWarning` including the host

### PR DESCRIPTION
**Pull request by sethmlarson**
Closes #1990

### CODE REVIEW

**Comment by pquentin** [comment]
The approach looks good, thanks! This breaks other tests, though, we'd have to fix that first

**Comment by sethmlarson** [comment]
@pquentin Yeah I couldn't run the TLS<1.2 tests on my local machine because Ubuntu disables it via OpenSSL config now (:tada:) and upon seeing how many failures there were threw my hands up and said "another time!" :)

**Comment by sethmlarson** [comment]
@pquentin Ready for a review now that tests are passing. The macOS 3.8 failure is strange, I'm not seeing any logs?

**Comment by pquentin** [comment]
If you click on "View raw logs", you can see that the failure is `test_timeout_errors_cause_retries`. Most of the flaky tests left are actually socket-level, and I don't know how to fix them properly yet. I'll re-run the tests.

The new warning makes running the TLS 1.0 and 1.1 tests quite noisy, is there a way to not display them in pytest?

**Comment by sethmlarson** [comment]
Hmm that's true, we can potentially set `ssl_version=...` on them so it doesn't trigger the warning?

**Comment by pquentin** [comment]
Yeah, if that sounds good to me if it's easy to do. (Sorry, haven't read the actual diff for now, I'm fighting with CI instead!)

Closing/reopening to rerun due to another socketlevel flaky test. (Tests are way more flaky when the US workday starts!)

**Review by pquentin — DISMISSED** [review]
Thanks! This looks good, though I'd like to see what can be done to reduce the warnings shown when running tests.

**Comment by sethmlarson** [comment]
@pquentin Yeah we might have to live with the noisiness for now, any other work-around is pretty painful. We'll get away from it after v2 though!

**Pull request merged**
