### PR TITLE
feat: Set the value of sock_and_verified for HTTPS to HTTP proxies

### LINKED ISSUE #3130: Incorrect behaviour of `proxy_is_verified`
### Subject

`proxy_is_verified` is never set for HTTPs to HTTP proxies. `proxy_is_verified` is set only at https://github.com/urllib3/urllib3/blob/main/src/urllib3/connection.py#L694 and the function `_connect_tls_proxy` containing this line is called only when we are creating a HTTP tunnel https://github.com/urllib3/urllib3/blob/main/src/urllib3/connection.py#L672. We would have to set the value for `proxy_is_verified` for scenarios when we are not using a TLS-in-TLS tunnel and instead setting up a TLS connection for HTTPs to HTTP case.

More context - https://github.com/urllib3/urllib3/pull/3070#pullrequestreview-1607114075

### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import ssl
import urllib3

print("OS", platform.platform()) # OS macOS-13.4.1-arm64-arm-64bit
print("Python", platform.python_version()) # Python 3.10.12
print(ssl.OPENSSL_VERSION) # OpenSSL 3.1.1 30 May 2023
print("urllib3", urllib3.__version__) # urllib3 1.26.14
```

### Steps to Reproduce

You can add a `print` statement to print `proxy_is_verified` for `HTTPS` to `HTTP` connection. The value of `proxy_is_verified` is set to `None` and never updated to `False` for the following example. 

```python
proxy = urllib3.ProxyManager('https://127.0.0.1:8443', cert_reqs='NONE')
res = proxy.request('GET', 'https://bff.familyid.samagra.io')
```

### Expected Behavior
`proxy_is_verified` set to `False` or `True` appropriately. 

### Actual Behavior

According to this comment in code if we are connected to proxy, it should not be `Nonfe` https://github.com/urllib3/urllib3/blob/d9f85a749488188c286cd50606d159874db94d5f/src/urllib3/connection.py#L120

But `proxy_is_verified` is set to `None` instead of `False`

What happens instead.

For `HTTPS` proxy connection to `HTTP` host, `proxy_is_verified` is never set properly. `proxy_is_verified` is set appropriately for `HTTPS` to `HTTPS` connections.

### PR DESCRIPTION
**Pull request by tushar5526**
Closes #3130

### CODE REVIEW

**Review by illia-v — CHANGES_REQUESTED** [review]
@tushar5526 can we approach this in a way that fixes `proxy_is_verified` and `is_verified` for all possible cases?

Making tests pass after a change like this may be a good first step:
```diff
diff --git a/test/with_dummyserver/test_proxy_poolmanager.py b/test/with_dummyserver/test_proxy_poolmanager.py                                                                                                                                                                                                                                                                                                      
index 9d5f9076..05ba4b3f 100644                                                                                                                                                                                                                                                                                                                                                                                     
--- a/test/with_dummyserver/test_proxy_poolmanager.py                                                                                                                                                                                                                                                                                                                                                               
+++ b/test/with_dummyserver/test_proxy_poolmanager.py                                                                                                                                                                                                                                                                                                                                                               
@@ -66,17 +66,33 @@ class TestHTTPProxyManager(HTTPDummyProxyTestCase):                                                                                                                                                                                                                                                                                                                                             
         with proxy_from_url(self.proxy_url, ca_certs=DEFAULT_CA) as http:                                                                                                                                                                                                                                                                                                                                          
             r = http.request("GET", f"{self.http_url}/")                                                                                                                                                                                                                                                                                                                                                           
             assert r.status == 200                                                                                                                                                                                                                                                                                                                                                                                 
+            pool = list(http.pools._container.values())[-1]                                                                                                                                                                                                                                                                                                                                                        
+            connection = pool.pool.queue[-1]                                                                                                                                                                                                                                                                                                                                                                       
+            assert connection.is_verified is False                                                                                                                                                                                                                                                                                                                                                                 
+            assert connection.proxy_is_verified is False                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                    
             r = http.request("GET", f"{self.https_url}/")                                                                                                                                                                                                                                                                                                                                                          
             assert r.status == 200                                                                                                                                                                                                                                                                                                                                                                                 
+            pool = list(http.pools._container.values())[-1]                                                                                                                                                                                                                                                                                                                                                        
+            connection = pool.pool.queue[-1]                                                                                                                                                                                                                                                                                                                                                                       
+            assert connection.is_verified is True                                                                                                                                                                                                                                                                                                                                                                  
+            assert connection.proxy_is_verified is False                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                    
     def test_https_proxy(self) -> None:                                                                                                                                                                                                                                                                                                                                                                            
         with proxy_from_url(self.https_proxy_url, ca_certs=DEFAULT_CA) as https:                                                                                                                                                                                                                                                                                                                                   
             r = https.request("GET", f"{self.https_url}/")                                                                                                                                                                                                                                                                                                                                                         
             assert r.status == 200                                                                                                                                                                                                                                                                                                                                                                                 
+            pool = list(https.pools._container.values())[-1]                                                                                                                                                                                                                                                                                                                                                       
+            connection = pool.pool.queue[-1]                                                                                                                                                                                                                                                                                                                                                                       
+            assert connection.is_verified is True                                                                                                                                                                                                                                                                                                                                                                  
+            assert connection.proxy_is_verified is True                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                    
             r = https.request("GET", f"{self.http_url}/")                                                                                                                                                                                                                                                                                                                                                          
             assert r.status == 200                                                                                                                                                                                                                                                                                                                                                                                 
+            pool = list(https.pools._container.values())[-1]                                                                                                                                                                                                                                                                                                                                                       
+            connection = pool.pool.queue[-1]                                                                                                                                                                                                                                                                                                                                                                       
+            assert connection.is_verified is False                                                                                                                                                                                                                                                                                                                                                                 
+            assert connection.proxy_is_verified is True                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                    
     def test_https_proxy_with_proxy_ssl_context(self) -> None:                                                                                                                                                                                                                                                                                                                                                     
         proxy_ssl_context = create_urllib3_context()   
```

**Comment by sethmlarson** [comment]
@tushar5526 I'm going to close this PR since it's been a bit since we've heard from you. Feel free to ping here if you intend to continue working. Thanks again!

**Comment by abebeos** [comment]
@tushar5526 , this got a bounty attached (https://github.com/urllib3/urllib3/issues/3130#event-10860179395), will you continue this? If not, I may give it a try.

**Comment by tushar5526** [comment]
Please go ahead @abebeos, I am not able to find much time rn :)

**Comment by abebeos** [comment]
@illia-v , @sethmlarson , after some hours break-pointing/single-stepping through the code, it seems that I cannot reach the instantiation of HTTP(S)Connection to trace a bug. Is there any possibility that the proxy pool manager bypasses the debugger (e.g. special techniques etc.)? (VSCode/Windows, everything works fine otherwise)

**Comment by abebeos** [comment]
False alarm, usual VSCode strangenesses. All good!

**Pull request closed without merging**
