### PR TITLE
Uninstall oclint to ensure gcc can be brew upgraded

### PR DESCRIPTION
**Pull request by SethMichaelLarson**

### CODE REVIEW

**Comment by pquentin** [comment]
I think the fix is `brew cask uninstall oclint`: https://github.com/travis-ci/travis-ci/issues/8826. The gdal issue is only a warning, not an error.

**Comment by SethMichaelLarson** [comment]
Thanks @pquentin! I'm very much in the dark about macOS and Homebrew. How'd you go about debugging this particular issue so I can learn to do so better in the future?

**Comment by pquentin** [comment]
The steps I followed:

* Looking at a failing macOS build such as: https://travis-ci.org/urllib3/urllib3/jobs/445273967
* Grep for "error:", see that the only error is:

        ==> Installing gdal dependency: gcc
        ==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.high_sierra.bottl
        ######################################################################## 100.0%
        ==> Pouring gcc-8.2.0.high_sierra.bottle.1.tar.gz
        Error: The `brew link` step did not complete successfully
        The formula built, but is not symlinked into /usr/local
        Could not symlink include/c++
        Target /usr/local/include/c++
        already exists. You may want to remove it:
          rm '/usr/local/include/c++'
        To force the link and overwrite all conflicting files:
          brew link --overwrite gcc
        To list all files that would be deleted:
          brew link --overwrite --dry-run gcc
        Possible conflicting files are:
        /usr/local/include/c++ -> /usr/local/Caskroom/oclint/0.13.1,17.4.0/oclint-0.13.1/include/c++

* Notice the last line, which says oclint conflicts (Caskroom is where homebrew installs packages)
* Search for `travis homebrew oclint gcc`, and find the travis github issue above which suggests uninstalling oclint first

**Comment by SethMichaelLarson** [comment]
Totally missed the name of the other package in the conflicting files error. I'll know what to look for next time. :)

**Pull request merged**
