### PR TITLE
Use curl to test our Hypercorn server can speak HTTP/2

### PR DESCRIPTION
**Pull request by sethmlarson**
Talk about bootstrapping, we need a way to make sure Hypercorn can actually speak HTTP/2 before urllib3 is able to. Created this simple test using `curl` which easily handles that task for us.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
LGTM if CI passes!

I suspect Windows will fail as curl isn't installed there: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

**Comment by sethmlarson** [comment]
@pquentin Appears curl might be on Windows anyways? The tests are failing with failing to match something on the output (might be due to different backends w/ curl?)

**Comment by pquentin** [comment]
The curl available on Windows VMs does not speak HTTP/2, which explains the failure.

**Comment by sethmlarson** [comment]
Going to merge since none of the failures are related to this PR. We're passing on all the OSes.

**Pull request merged**
