### PR TITLE
WIP: remove self.addCleanup for pytest migration

### PR DESCRIPTION
**Pull request by RatanShreshtha**
I have opened this PR to get an early feedback on few things like https://github.com/urllib3/urllib3/blob/a1f6d1080d1a5236915c10fb6cbb673c945ba4a9/test/with_dummyserver/test_proxy_poolmanager.py#L34-L48 
What should be the right way to rewrite the test ? 

And 

In https://github.com/urllib3/urllib3/blob/a1f6d1080d1a5236915c10fb6cbb673c945ba4a9/test/with_dummyserver/test_https.py#L526-L569.

I have noticed that first https_pool is created but it is not used is it intentional ?

### CODE REVIEW

**Comment by pquentin** [comment]
I would rewrite test_nagle_proxy like this:

```
def test_nagle_proxy(self):
        """ Test that proxy connections do not have TCP_NODELAY turned on """
        with proxy_from_url(self.proxy_url) as http:
            hc2 = http.connection_from_host(self.http_host, self.http_port)
            try:
                conn = hc2._get_conn()
                hc2._make_request(conn, "GET", "/")
                tcp_nodelay_setting = conn.sock.getsockopt(
                    socket.IPPROTO_TCP, socket.TCP_NODELAY
                )
                assert tcp_nodelay_setting == 0, (
                    "Expected TCP_NODELAY for proxies to be set "
                    "to zero, instead was %s" % tcp_nodelay_setting
                )
            finally:
                conn.close()
                # alternatively, use hc2._put_conn(conn) to put the connection
                # back into the pool so that its get closed when we exit from
                # the proxy_from_url context
```

(Also, `proxy_from_url` has changed over the time but no longer provides any value. So we could remove it and use `with ProxyManager(self.proxy_url) as http` instead.)

> I have noticed that first https_pool is created but it is not used is it intentional ?

I don't know what was the intention behind https://github.com/urllib3/urllib3/commit/b4e5a8f491eb45ef9bfac5b24b118ad022babf89 but I don't think it's useful.

**Comment by RatanShreshtha** [comment]
thanks @pquentin your version of test looks much more readable than the version I thought, maybe @sethmlarson has more idea about https://github.com/urllib3/urllib3/commit/b4e5a8f491eb45ef9bfac5b24b118ad022babf89.

**Comment by sethmlarson** [comment]
I think you're free to remove the duplicate pool.

**Comment by RatanShreshtha** [comment]
I have removed all the `self.addCleanup` calls and the tests seems to pass everywhere except on python 3.8, I don't know why it is so ?

**Comment by RatanShreshtha** [comment]
All the tests are failing for python3.8 in travis for all the pull requests, but I am able to run the tests for python3.8 in my local machine.

**Comment by RatanShreshtha** [comment]
what is the next thing to do for this PR?

**Comment by sethmlarson** [comment]
All that's left is for me to remember to merge this! ;)

**Comment by sethmlarson** [comment]
Thanks for this @RatanShreshtha!

**Pull request merged**
