### PR TITLE
Fix up typo - replace adddres with address (#1644).

### PR DESCRIPTION
**Pull request by timgates42**

### CODE REVIEW

**Comment by timgates42** [comment]
Addresses issue #1644

**Comment by sethmlarson** [comment]
Thanks for this! The package you're modifying is actually vendored in from https://github.com/python-hyper/rfc986. Mind making the change on that repository?

**Comment by pquentin** [comment]
Fixed a typo in the link: https://github.com/python-hyper/rfc3986/

**Comment by sethmlarson** [comment]
Typos galore! :)

**Comment by timgates42** [comment]
thx - raised and submitted a fix in that repo - https://github.com/python-hyper/rfc3986/issues/60

**Comment by timgates42** [comment]
also removed the rfc3986 part and left just the unit test typo fix in #1742

**Comment by pquentin** [comment]
@timgates42 thanks! I'm still seeing the rfc3986 fix from GitHub, do you know why?

**Comment by timgates42** [comment]
Oh sorry - where do you see it - in your pull requests review requested screen? I sometimes get left over closed pull requests still showing and if I delete the branch it sometimes fixes the issue - I'll try that here.

**Comment by pquentin** [comment]
@timgates42 looks everything is fine now as your other pull request got merged, and I have to admit I no longer know what I was referring to in my comment above!

**Pull request closed without merging**
