### PR TITLE
Rewrite test_selectors.py to be pytest-style

### PR DESCRIPTION
**Pull request by alexwlchan**
Related: #1160.

### CODE REVIEW

**Comment by alexwlchan** [comment]
Note: although removing unittest entirely from the urllib3 codebase would be a significant challenge, dropping the unittest2 dependency is probably more feasible – and this patch continues to snip away at its ties.

**Comment by Lukasa** [comment]
Looks like removing unittest2 was a bit aggressive: check the appveyor 2.6 failure.

**Comment by alexwlchan** [comment]
> Looks like removing unittest2 was a bit aggressive: check the appveyor 2.6 failure.

Well that’s thoroughly sucktacular.

**Comment by Lukasa** [comment]
Now it's flake8's turn to punish you for your hubris. 😉

**Comment by Lukasa** [comment]
What the hell is codecov talking about now?

**Comment by pquentin** [comment]
test_selectors.py was removed https://github.com/urllib3/urllib3/pull/1358: I think this pull request can be safely closed.

**Comment by SethMichaelLarson** [comment]
Good call!

**Pull request closed without merging**
