### PR TITLE
Striped square brackets from host IP

### PR DESCRIPTION
**Pull request by derekhiggins**
When comparing host IP to a cert subjectAltName->"IP Address"
ensure were strip square brackets from IPv6 addresses.

Fixes: https://github.com/urllib3/urllib3/issues/2240

### CODE REVIEW

**Comment by derekhiggins** [comment]
I also looked into stripping out the brackets further up the stack
in  PoolManager.connection_from_host , but this causes the CONNECT to the proxy to break 
`1621610373.972      3 fd00:1101::1 TCP_TUNNEL/200 1050 CONNECT [fd00:1101::7d50:2883:3df9:68ce]:9999 - HIER_DIRECT/fd00:1101::7d50:2883:3df9:68ce -                                                               
` 
vs.
`1621606788.209    257 fd00:1101::1 TAG_NONE/503 0 CONNECT fd00:1101 - HIER_NONE/- -
`

**Review by hramezani — APPROVED** [review]
I am not sure about the right place to stripping out the brackets would be `match_hostname` function, but the implementation and tests look good to me.
Also, I think we need to backport it to 1.26.x

**Comment by sethmlarson** [comment]
I wonder if there's a better place to do this within the proxy flow?

**Comment by derekhiggins** [comment]
> I wonder if there's a better place to do this within the proxy flow?

The alternative I tried was to strip them out in PoolManager.connection_from_host but this failed.

Looking a bit deeper this appears to be because HTTPSConnection.set_tunnel requires the square brackets to be in place. Which I guess is why they were left in place in the first place. I could strip them out in connection_from_host and then put them
back in for the call to set_tunnel but I'm not sure if there are other places where I'd need to put them back.

**Comment by derekhiggins** [comment]
Rebased

**Review by sethmlarson — APPROVED** [review]
This much more localized implementation looks good to me, thank you!

Would love an integration test too, especially one that tests proxies too (cc @jalopezsilva).

The integration test on 1.26.x will probably reveal a slightly more complex route for 1.26.x because iirc we don't unconditionally use our implementation of `ssl_match_hostname()` there. Will have to take a peek.

**Review by sethmlarson — APPROVED** [review]
LGTM

**Review by jalopezsilva — APPROVED** [review]
Looks good to me!

**Comment by jalopezsilva** [comment]
@sethmlarson, should I add the proxy integration directly here or wait until we merge it?

**Comment by sethmlarson** [comment]
@jalopezsilva Let's merge this then you can add the proxy integration after. I think this one may be non-trivial to backport, maybe you can look at this a bit too?

**Pull request merged**
