### PR TITLE
Add server_hostname to SSL_KEYWORDS

### PR DESCRIPTION
**Pull request by rabi**
It is only relevant for HTTPSConnection.

Resolves: #2534

### CODE REVIEW

**Review by kajinamit — APPROVED** [review]

**Comment by cdent** [comment]
Looks like black wants a minor change before all tests will pass, but this looks good to me and fixes the issues being seen in gabbi (where a PoolManager can be used with mixed schemes).

**Review by sethmlarson — APPROVED** [review]
Thank you for this change, could you add a test case that catches this error so we don't regress in the future?

**Comment by pquentin** [comment]
(We'll also have to backport this to the 1.26.x branch))

**Comment by sethmlarson** [comment]
Very true! Our team can handle the backport after this PR is merged.

**Comment by rabi** [comment]
>  could you add a test case that triggers the error so we don't regress in the future

Added a test. Hope that would suffice for now.

**Review by hramezani — APPROVED** [review]

**Review by sethmlarson — APPROVED** [review]
LGTM, thanks!

**Comment by hramezani** [comment]
@sethmlarson I will create a patch to backport it to the `1.26.x`.

**Pull request merged**
