### PR TITLE
make sure test_ssl_failed_fingerprint_verification tests fingerprint …

### PR DESCRIPTION
**Pull request by graingert**
…verficiation

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Thanks! LGTM

**Comment by graingert** [comment]
@sethmlarson I think @pquentin is -1 on this PR

**Comment by graingert** [comment]
@pquentin thinks assert_fingerprint should imply cert_reqs="CERT_NONE"

**Review by pquentin — APPROVED** [review]
> I think @pquentin thinks assert_fingerprint should imply cert_reqs="CERT_NONE"?

I do, but that ship has sailed. I would love a follow up PR documenting `assert_fingerprintˋ in the advanced usage section though.

LGTM!

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
