### PR TITLE
remove ssl_match_hostname

### PR DESCRIPTION
**Pull request by dulmandakh**
Remove **ssl_match_hostname** package, and replace its usage with **ssl** module.

### CODE REVIEW

**Comment by sethmlarson** [comment]
The `ssl` module isn't always available and sometimes doesn't support features that we need like the ability to disable checking `commonName` on Python 3.6.

**Comment by pquentin** [comment]
@dulmandakh Would you be interested in moving `ssl_match_hostname` to `urllib3.utils` now that https://github.com/urllib3/urllib3/pull/2186 landed?

**Comment by hramezani** [comment]
> @dulmandakh Would you be interested in moving `ssl_match_hostname` to `urllib3.utils` now that #2186 landed?

@pquentin Does it mean to move `ssl_match_hostname` directory from `urllib3.packages` to `urllib3.utils`? If so, I can work on it.

**Comment by pquentin** [comment]
@hramezani Sure, please do!

**Pull request closed without merging**
