### PR TITLE
Release 1.26.16

### PR DESCRIPTION
**Pull request by sethmlarson**
* [x]  See if all tests, including integration, pass
* [x]  Get the release pull request approved by a [CODEOWNER](https://github.com/urllib3/urllib3/blob/main/.github/CODEOWNERS)
* [ ]  Squash merge the release pull request with message "`Release <VERSION>`"
* [ ]  Tag with X.Y.Z, push tag on urllib3/urllib3 (not on your fork, update `<REMOTE>` accordingly)
  * Notice that the `<VERSION>` shouldn't have a `v` prefix (Use `1.26.6` instead of `v.1.26.6`)
  * ```
    git tag -s -a '<VERSION>' -m 'Release: <VERSION>'
    git push <REMOTE> --tags
    ```
* [ ]  Execute the `publish` GitHub workflow. This requires a review from a maintainer.
* [ ]  Ensure that all expected artifacts are added to the new GitHub release. Should
       be one `.whl`, one `.tar.gz`, and one `multiple.intoto.jsonl`. Update the GitHub
       release to have the content of the release's changelog.
* [ ]  Announce on:
  * [ ]  Twitter
  * [ ]  Discord
  * [ ]  OpenCollective
* [ ]  Update Tidelift metadata
* [ ]  If this was a 1.26.x release, add changelog to the `main` branch

### CODE REVIEW

**Review by illia-v — APPROVED** [review]

**Review by pquentin — APPROVED** [review]

**Comment by pquentin** [comment]
Publishing the released to PyPI failed: https://github.com/urllib3/urllib3/actions/runs/5056259780/jobs/9073810866#step:5:13

Looks like the trusted publishing addition in #3029 did not work. @sethmlarson @woodruffw Any ideas what the issue is?

**Comment by pquentin** [comment]
Awesome, thanks! Does that fix also apply to 2.0 releases?

**Comment by sethmlarson** [comment]
@woodruffw Nope it was all on me, I configured thinking we had the GitHub Environment covering the publish job :) Thanks for the reply and getting us started using trusted publishers! I will say this brings to mind that it'd be great if there was some ability to dry-run your configuration. This is always the unfortunate part of configuring something in your release pipeline, you won't know it *actually* works until prime time.

**Comment by woodruffw** [comment]
> I will say this brings to mind that it'd be great if there was some ability to dry-run your configuration. This is always the unfortunate part of configuring something in your release pipeline, you won't know it actually works until prime time.

Yeah, that's a great idea -- I'll file a tracking issue for that! 

As a stop-gap: trusted publishing also works on TestPyPI, so you can use that instance as a guinea pig 🙂

**Pull request merged**
