### PR TITLE
Update RECENT_DATE to 2019-1-1

### PR DESCRIPTION
**Pull request by sethmlarson**
First PR from the new laptop! :)

### CODE REVIEW

**Comment by theacodes** [comment]
Could we just... idk.. generate this with `utcnow()` and `timedelta`?

**Comment by pquentin** [comment]
Sure, but we need to do it on a system where we know that the time is correct! So this could be done as part of the release process.

**Comment by sethmlarson** [comment]
If this value was generated right before a release (for example on one of Travis's builders) you'd run into problems with users who bundle.  They wouldn't get a `RECENT_DATE`.

**Comment by sethmlarson** [comment]
If we started using pre-commit we could create a custom one just for this value. :)

**Pull request merged**
