### PR TITLE
Add dark logo in docs dark mode

### LINKED ISSUE #2028: urllib3 logo is unreadable in docs in dark mode
This is a recent Furo addition, you can see it in this pull request build: https://urllib3--2026.org.readthedocs.build/en/2026/index.html. Here's what I see (with Firefox on macOS with dark mode enabled):

urllib3 logo in dark mode in docs

I'm not sure what the correct fix is here. The obvious one would be to force a white background. I guess we could also... add a dark mode urllib3 logo, by switching black letters to white?

(The rest of the content looks good, even if the contrast seems low to me.)

### PR DESCRIPTION
**Pull request by pquentin**
Closes #2028 

Did not test locally as the images links are wrong when I just open index.html. Let's see if that works in the RTD build.

### CODE REVIEW

**Comment by pquentin** [comment]
@pradyunsg I can't get this to work :) It looks like the logos are not even exported in the _static folder

**Comment by pradyunsg** [comment]
@pquentin As mentioned in https://pradyunsg.me/furo/customisation/logo/#different-logos-for-light-and-dark-mode:

> The filenames must be relative to the html_static_path folder.

This is because Sphinx special cases handling of `html_logo`. That logic is non-trivial to implement for the `html_theme_options` values, without doing really hacky things that'd make me feel very dirty.

Here's what'll likely work:

- Put the files in an `_static` folder (i.e. `docs/_static/dark-logo.svg`, `docs/_static/banner.svg`).
- ```py
  html_static_path = "_static"

  html_theme_options = {
    "light_logo": "banner.svg",
    "dark_logo": "dark-logo.svg",
  }
  ```

I'll elaborate on this in the documentation you were looking at! :)

**Comment by sethmlarson** [comment]
Looks like RTD is showing both logos now: https://urllib3--2042.org.readthedocs.build/en/2042/

**Comment by pquentin** [comment]
@pradyunsg Thanks, that helped! I should have followed the link in your docs. The new version is much clearer, thanks! However, as @sethmlarson mentioned, I'm seeing both logos in both modes on Firefox and Chrome: https://urllib3--2042.org.readthedocs.build/en/2042/

Capture d’écran 2020-11-10 à 22 17 51

I'd like to make it clear that I'm not expecting support from you! I probably understand enough CSS to take a look at this issue, but not today, and I thought you would be interested in being aware of it anyway.

**Comment by pradyunsg** [comment]
Oh no. I did a boo-boo.

**Comment by pradyunsg** [comment]
This should be fixed by https://github.com/pradyunsg/furo/commit/3d89d56d5e7722fb450bdde2e1433f53ae1dd3d3 -- I'll cut the release once I'm done writing these last few paragraphs of documentation. :)

**Comment by pquentin** [comment]
Trying again since this was released.

**Comment by pquentin** [comment]
@urllib3/maintainers Now that this works, we need to decide whether the white logo a good idea or not :)

@ryanfeeley What do you think?

**Comment by sethmlarson** [comment]
Spoke with @ryanfeeley on Twitter and it's a :+1:, we can merge this! :tada:

**Pull request merged**
