### PR TITLE
fix test_no_ssl by using subprocess to disable ssl import

### PR DESCRIPTION
**Pull request by graingert**
fixes https://github.com/urllib3/urllib3/issues/2972

### CODE REVIEW

**Comment by graingert** [comment]
annoyingly this fails coverage with `src/urllib3/connection.py                  272      4    99%   32-35, 878`

**Comment by pquentin** [comment]
There are ways to fix this: https://coverage.readthedocs.io/en/stable/subprocess.html. Do they apply here?

**Review by sethmlarson — APPROVED** [review]
LGTM, thanks!

**Comment by sethmlarson** [comment]
Ah, only looked at the PR and not the coverage status, I hope you can figure out the subprocess coverage?

**Pull request closed without merging**
