### PR TITLE
Release 2.0.3

### PR DESCRIPTION
**Pull request by sethmlarson**
* [x]  See if all tests, including integration, pass
* [x]  Get the release pull request approved by a [CODEOWNER](https://github.com/urllib3/urllib3/blob/main/.github/CODEOWNERS)
* [ ]  Squash merge the release pull request with message "`Release <VERSION>`"
* [ ]  Tag with X.Y.Z, push tag on urllib3/urllib3 (not on your fork, update `<REMOTE>` accordingly)
  * Notice that the `<VERSION>` shouldn't have a `v` prefix (Use `1.26.6` instead of `v.1.26.6`)
  * ```
    git tag -s -a '<VERSION>' -m 'Release: <VERSION>'
    git push <REMOTE> --tags
    ```
* [ ]  Execute the `publish` GitHub workflow. This requires a review from a maintainer.
* [ ]  Ensure that all expected artifacts are added to the new GitHub release. Should
       be one `.whl`, one `.tar.gz`, and one `multiple.intoto.jsonl`. Update the GitHub
       release to have the content of the release's changelog.
* [ ]  Announce on:
  * [ ]  Twitter
  * [ ]  Discord
  * [ ]  OpenCollective
* [ ]  Update Tidelift metadata
* [ ]  If this was a 1.26.x release, add changelog to the `main` branch

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks! LGTM.

**Review by illia-v — DISMISSED** [review]

**Comment by illia-v** [comment]
BTW, https://github.com/urllib3/urllib3/commit/ffa2b634392a389da7033834fa485fd648d37e42 missed a news entry, but it should be mentioned in the release notes probably
And Open Graph info added in https://github.com/urllib3/urllib3/pull/3034 needs a revisit (see comments in the PR), but I think it doesn't block the release; reverting it for now may be an option too

**Comment by pquentin** [comment]
https://github.com/urllib3/urllib3/pull/3055 needs to be added to the changelog too.

**Review by pquentin — APPROVED** [review]
The new changelog looks good to me.

**Pull request merged**
