### PR TITLE
Streaming file uploads

### LINKED ISSUE #624: Twice memory usage in `encode_multipart_formdata`
Basically, if you wants to upload file like 1GB it will cost you 2GB RAM.

```
Filename: /Users/kyrylo/.virtualenvs/drsdk/lib/python2.7/site-packages/requests/packages/urllib3/filepost.py

Line #    Mem usage    Increment   Line Contents
================================================
    59    981.3 MiB      0.0 MiB   @profile
    60                             def encode_multipart_formdata(fields, boundary=None):
    61                                 """
    62                                 Encode a dictionary of ``fields`` using the multipart/form-data MIME format.
    63                             
    64                                 :param fields:
    65                                     Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
    66                             
    67                                 :param boundary:
    68                                     If not specified, then a random boundary will be generated using
    69                                     :func:`mimetools.choose_boundary`.
    70                                 """
    71    981.3 MiB      0.0 MiB       body = BytesIO()
    72    981.3 MiB      0.0 MiB       if boundary is None:
    73    981.3 MiB      0.0 MiB           boundary = choose_boundary()
    74                             
    75   1920.7 MiB    939.4 MiB       for field in iter_field_objects(fields):
    76    981.3 MiB   -939.4 MiB           body.write(b('--%s\r\n' % (boundary)))    77                             
    78    981.3 MiB      0.0 MiB           writer(body).write(field.render_headers())
    79    981.3 MiB      0.0 MiB           data = field.data
    80                             
    81    981.3 MiB      0.0 MiB           if isinstance(data, int):
    82                                         data = str(data)  # Backwards compatibility
    83                             
    84    981.3 MiB      0.0 MiB           if isinstance(data, six.text_type):
    85                                         writer(body).write(data)
    86                                     else:
    87   1920.7 MiB    939.4 MiB               body.write(data)
    88                             
    89   1920.7 MiB      0.0 MiB           body.write(b'\r\n')
    90                             
    91   1920.7 MiB      0.0 MiB       body.write(b('--%s--\r\n' % (boundary)))
    92                             
    93   1920.7 MiB      0.0 MiB       content_type = str('multipart/form-data; boundary=%s' % boundary)
    94                             
    95   2000.1 MiB     79.4 MiB       return body.getvalue(), content_type
```

P.S. using this profiler https://pypi.python.org/pypi/memory_profiler

### PR DESCRIPTION
**Pull request by pquentin**
Closes #624 

This is nothing more than #1030 rebased on top of the current master. I havan't checked memory usage yet, but would be happy to get a review. I'm not really satisified with the encode() function, is it possible to avoid it now that we're Python 3 only?

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Is there a reason not to use the streaming encode from the toolbelt and adapt it here to avoid the requests-isms (namely importing urllib3 from it's packages for the things in this very module)?

Also a chunk_size of `8192` is extremely slow and small for most people. http.client finally allowed for users to configure that in 3.9. As it stands this looks like an iterator which (iirc) we treated as chunked TE instead of a file with a content-length (and most folks want a content-length, not chunked TE).

**Comment by sethmlarson** [comment]
@sigmavirus24 requests-toolbelt is Apache-2.0 licensed compared to our MIT, this presents a problem?

**Comment by sigmavirus24** [comment]
I wrote all the code and am happy to contribute it here under MIT. Also I give y'all permission to just copy it under MIT

**Comment by pquentin** [comment]
@sigmavirus24 Are you referring to https://github.com/requests/toolbelt/blob/master/requests_toolbelt/streaming_iterator.py? I'd be happy to include that instead. The only limitation that I see compared to this pull request is that you need to know the size in advance, but that's probably not a huge deal.

**Comment by sigmavirus24** [comment]
I was referring to https://github.com/requests/toolbelt/blob/master/requests_toolbelt/multipart/encoder.py

**Pull request closed without merging**
