### PR TITLE
Make sure README looks good in GitHub dark mode

### PR DESCRIPTION
**Pull request by chetanugale**
Closes https://github.com/urllib3/urllib3/issues/2103

Light mode:
light_theme
Dark mode:
dark_theme

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks for this! It's the only thing we can do to improve the situation. However, I'm not sure what to think. In "Dark dimmed" mode, the old logo is not that bad. But hard to read in "Default dark". The new logo is readable in all settings, but hard on the eyes.

What do others think?

(Note that we'll have to adjust details like the border of the name of the file if this gets accepted, but let's not discuss those details right now.)

**Comment by sethmlarson** [comment]
Yeah I think a thin white border around the lettering+symbols would be enough here and probably would look more deliberate as well :)

**Comment by pquentin** [comment]
This looks great! Do we need to make the image slightly bigger so that the bottom lettering of the b isn't cut off?

**Comment by sethmlarson** [comment]
Agree with Quentin about the tiny bit of cutoff. Looks fantastic!! 🤩

**Comment by sethmlarson** [comment]
Screenshot from 2021-08-12 07-59-06

That looks really really good, thank you!

**Comment by sethmlarson** [comment]
@chetanugale Not to be too nitpicky but can we increase the background a tiny bit more? I think there's a little cutoff on the right edge of the 3 but after that it's perfect :muscle:

**Comment by sethmlarson** [comment]
Now there's some cutoff on the left, if you need to we can increase the size of the canvas beyond 400 :)

**Comment by sethmlarson** [comment]
@chetanugale As an aside I'm planning on tweeting this out once it's merged, do you have a Twitter handle I can tag to credit?

**Comment by pquentin** [comment]
Should we call this file `banner_github.svg`? That way we don't touch the existing dark/white logo in the docs.

Or should we use this in the docs too?

**Comment by chetanugale** [comment]
looks good?
Screenshot 2021-08-12 at 6 38 57 PM

**Comment by sethmlarson** [comment]
Yeah we should leave the banner used by the docs the same, this can be `banner-readme.svg` or `banner-github.svg`

**Comment by sethmlarson** [comment]
@chetanugale I think the `u` is still barely cutoff by 1 pixel on the left.

**Review by sethmlarson — APPROVED** [review]
LGTM, thank you so much for this!

**Comment by chetanugale** [comment]
> @chetanugale As an aside I'm planning on tweeting this out once it's merged, do you have a Twitter handle I can tag to credit?

**@duratan_it_is**

**Pull request merged**
