### PR TITLE
Add 1.26.17 to the current changelog

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Thanks Illia!

**Comment by pquentin** [comment]
Is it useful to list this twice? In 1.26.17 and 2.0.6

**Comment by illia-v** [comment]
> Is it useful to list this twice? In 1.26.17 and 2.0.6

In my opinion, it is useful to have 1.26.17 listed in the file. Not necessarily as a duplicate of 2.0.6, maybe just saying "Backported a security fix from 2.0.6"

**Comment by pquentin** [comment]
Fair enough. No need to change the wording

**Pull request merged**
