### PR TITLE
Handle https:///, https:/ and https:\ as https:// 

### PR DESCRIPTION
**Pull request by chetanugale**
Issue : https://github.com/urllib3/urllib3/issues/2368

Tested with :
url1=urllib3.util.parse_url('https:///www.attacker.com/a/b')
print("HOSTNAME:  " +str(url1.host))
print("PATH    :  " +str(url1.path))
url2=urllib3.util.parse_url('https:/www.attacker.com/a/b')
print("HOSTNAME:  " +str(url2.host))
print("PATH    :  " +str(url2.path))
url3=urllib3.util.parse_url('https:\www.attacker.com/a/b')
print("HOSTNAME:  " +str(url3.host))
print("PATH    :  " +str(url3.path))

response:

HOSTNAME:  www.attacker.com
PATH    :  /a/b
HOSTNAME:  www.attacker.com
PATH    :  /a/b
HOSTNAME:  www.attacker.com
PATH    :  /a/b

### CODE REVIEW

**Comment by pquentin** [comment]
Regardless of the code here, it's interesting that the requests test suite is using `http:/badproxyurl:3128` as an URL that should fail to parse. We'll have to submit a fix there to use a different URL!

**Comment by chetanugale** [comment]
@pquentin @SethMichaelLarson any inputs for this PR ?

**Comment by pquentin** [comment]
@chetanugale We're sorry that we haven't reviewed this yet. We know that we should, but URL parsing changes are always scary as we had many vulnerabilities here in the past, and it's easy to make subtle mistakes. Unfortunately I can't promise any timeline for a review here. :(

**Comment by timmc** [comment]
I don't think this change should be accepted -- see comments on issue: https://github.com/urllib3/urllib3/issues/2368#issuecomment-1086726748

**Comment by sethmlarson** [comment]
I'm not confident enough to make a call that this is the right thing to do, so I'm going to decline it for now. Sorry it took so long to reach this conclusion. See https://github.com/urllib3/urllib3/issues/2368#issuecomment-1086755912 for more info.

**Pull request closed without merging**
