### PR TITLE
Remove ALPN_PROTOCOLS export from urllib3.util

### PR DESCRIPTION
**Pull request by pquentin**
If it's in two places, `urllib3.http2.inject_into_urllib3()` needs to update both places.

This was suggested in https://github.com/urllib3/urllib3/pull/3324#discussion_r1493830543.

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Hopefully no one is messing with our `ALPN_PROTOCOLS`?

**Comment by pquentin** [comment]
I don't know honestly. I'm not sure this change is a net benefit.

**Comment by sethmlarson** [comment]
Maybe we deprecate it with a module level __getattr__?

**Comment by sethmlarson** [comment]
@pquentin Shall we close this PR if we're not sure it's a net-benefit?

**Comment by pquentin** [comment]
Yes, agreed.

**Pull request closed without merging**
