### PR TITLE
Remove assert_hostname from hostname check

### PR DESCRIPTION
**Pull request by ddebeau**
Closes: https://github.com/urllib3/urllib3/issues/2126

### CODE REVIEW

**Comment by sethmlarson** [comment]
`assert_hostname=True` isn't supported and isn't documented anywhere as far as I can tell? `assert_hostname` can either be a hostname or `False` to disable it. Instead of removing we should instead document `assert_hostname` better?

**Comment by ddebeau** [comment]
@sethmlarson Passing a bool to the underlying function `ssl.match_hostname` will result in an exception.

https://github.com/python/cpython/blob/b5711c940f70af89f2b4cf081a3fcd83924f3ae7/Lib/ssl.py#L371

**Comment by sethmlarson** [comment]
I'm aware, I'm suggesting that passing `True` isn't a documented or supported input for `assert_hostname` so there isn't anything to fix/remove here aside from documenting usage better.

**Comment by ddebeau** [comment]
I don't understand why you want to leave the possibility for a bool to be passed to `_match_hostname` when it will result in an exception. I don't see the purpose of having it there.

Accepting only `False` instead of `True` or `False` seems bizarre.

**Comment by sethmlarson** [comment]
Closing this due to inactivity.

**Comment by pquentin** [comment]
@sethmlarson For what it's worth I have the same question than @ddebeau above. Is the idea that we don't want to break our API?

**Comment by sethmlarson** [comment]
It wouldn't be a breakage, I'd accept a PR that allows for `assert_hostname=True`

**Comment by pquentin** [comment]
What I had not understood in your initial explanation, Seth, is that `assert_hostname` could also be a host. It's not only a boolean!

> Accepting only False instead of True or False seems bizarre.

@ddebeau This isn't true: we accept False, None and an actual hostname.

Actually, it would be better to document is as a Optional[str], an optional hostname: since the code uses `or`, it works too. And it would avoid the confusion. Accepting `True` isn't useful, there are many other places where the code will break by sending the wrong type. We should continue to accept `False` for backwards compatibility, though.

**Pull request closed without merging**
