### PR TITLE
Fix HTTPResponse.read(0) as first read call

### PR DESCRIPTION
**Pull request by pquentin**
HTTPResponse uses a bytes buffer since https://github.com/urllib3/urllib3/pull/2798. This buffer fails if we call get(n) and the buffer is empty, but that means that if the first call to HTTPResponse.read(n) is done with n = 0, the read() call fails. I don't think there is a good reason to do that in practice, but requests-toolbelt has a unit test that does it, which currently fails with urllib3 2.0: https://github.com/requests/toolbelt/actions/runs/4834111890/jobs/8614945073?pr=356

### CODE REVIEW

**Review by sethmlarson — DISMISSED** [review]
Great find, thanks for this!

**Comment by graingert** [comment]
I think the failure in

```
FAILED test/contrib/test_pyopenssl.py::TestSocketSSL::test_ssl_custom_validation_failure_terminates - AssertionError: The socket was not terminated
assert False
 +  where False = <bound method Event.wait of <threading.Event object at 0x00000255E46E6108>>(0.5)
 +    where <bound method Event.wait of <threading.Event object at 0x00000255E46E6108>> = <threading.Event object at 0x00000255E46E6108>.wait
```
is due to https://github.com/urllib3/urllib3/issues/2991

**Review by sethmlarson — APPROVED** [review]
LGTM, thanks Quentin!

**Comment by pquentin** [comment]
The failures are unrelated, merging.

**Pull request merged**
