### PR TITLE
Replace `pytest.yield_fixture` with `pytest.fixture`.

### PR DESCRIPTION
**Pull request by hramezani**
Fixes https://github.com/urllib3/urllib3/issues/2185

### CODE REVIEW

**Comment by hramezani** [comment]
Do the failing test related to my change :thinking: ? I can see they failed on my local setup as well.

**Comment by pquentin** [comment]
Yeah, this happened because #2178 and #2186 were merged separately. main is broken too: https://github.com/urllib3/urllib3/runs/2122811506.

(This issue was for new contributors, by the way, but thanks for tackling it anyway!)

**Comment by hramezani** [comment]
> This issue was for new contributors

Yes, you are right. Sorry for that :man_facepalming:

**Comment by sethmlarson** [comment]
Cycling CI

**Review by pquentin — APPROVED** [review]
Thanks!

**Pull request merged**
