### PR TITLE
Require mypy installation and add to contributors

### PR DESCRIPTION
**Pull request by savarin**
Addresses https://github.com/urllib3/urllib3/issues/1897, more specifically https://github.com/urllib3/urllib3/pull/1924#issuecomment-678282065.

Includes `mypy` as a requirement for the dev environment. Add to list of contributors.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks!

This time everything went fine, even codecov: https://codecov.io/gh/urllib3/urllib3/tree/f66cf3d20961220a72a8634e732a9285b3c7b720

I don't understand why it's red on GitHub, but this can be safely merged.

**Comment by savarin** [comment]
Closing and reopening to rerun test suite.

**Comment by sethmlarson** [comment]
Shouldn't we be adding `mypy` to be installed by `nox` within the `lint` task?

**Comment by pquentin** [comment]
Oh, you mean `session.install("mypy")` can work even if we're using Popen() to run mypy outside of the nox venv?

I just realized that `nox -s lint` is broken anyway: we don't look at returncode, and thus don't detect failures like "mypy isn't installed". And we should be using `["mypy", "--strict", "src/urllib3"]`, not "mypy --strict src/urllib3". Maybe there are other problems.

**Comment by pquentin** [comment]
I've added a few improvements.

 * Using a single string wasn't actually broken as we were using `shell=True`, but avoiding that is always good idea if possbile
 * It's useful to read the return code to make sure that mypy itself ran succesfully, but it's slightly tricky because we need to accept return code 1 which is "I found errors!"
 * I've switched to subprocess.run() which eliminates the need to do stdout decoding
 * I fixed a path error
 * I logged that mypy is being run, otherwise the errors appear to come fom flake8

**Comment by sethmlarson** [comment]
@pquentin It looks like the `text` parameter was only added to `subprocess.run()` in Python 3.7, maybe we need to bump our Python version running the Travis `lint` job? I'm going to bump that and make sure it passes.

**Comment by savarin** [comment]
> I've added a few improvements.
> 
> * Using a single string wasn't actually broken as we were using `shell=True`, but avoiding that is always good idea if possbile
> * It's useful to read the return code to make sure that mypy itself ran succesfully, but it's slightly tricky because we need to accept return code 1 which is "I found errors!"
> * I've switched to subprocess.run() which eliminates the need to do stdout decoding
> * I fixed a path error
> * I logged that mypy is being run, otherwise the errors appear to come fom flake8

@pquentin Nice! Much appreciate the additions and comments!

**Pull request merged**
