### PR TITLE
Move nox -s lint to GitHub Actions

### PR DESCRIPTION
**Pull request by pquentin**
Notice how much more verbose this is, I should try to find ways to factorize things a bit. Also, should we add this file to CODEOWNERS?

### CODE REVIEW

**Comment by pradyunsg** [comment]
May I suggest adopting pre-commit for managing the linters, and using the pre-commit GitHub action?

**Comment by sethmlarson** [comment]
Can add `.github/workflows` directory to CODEOWNERS once the deploy job is migrated to GitHub Actions :)

**Comment by pquentin** [comment]
@sethmlarson does that mean you're approving this change? :)

**Comment by pquentin** [comment]
@sethmlarson does that mean you're approving this change? :)

**Comment by sethmlarson** [comment]
Oh! Yes I can! Only reason I didn't is because I thought there was more work to do here for some reason :) thanks for the nudge

**Review by sethmlarson — APPROVED** [review]

**Comment by pradyunsg** [comment]
@sethmlarson Fair enough! I'll mention that `nox -s lint` that runs `pre-commit` is definitely straightforward -- https://github.com/pradyunsg/furo/blob/master/noxfile.py#L73-L82 -- and now I'mma stop being noisy about adopting pre-commit. :)

**Pull request merged**
