### PR TITLE
Release 1.25.7

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Comment by pquentin** [comment]
Yay, a release!

I think there are a few missing changelog entries:

 * Preserve chunked parameter on retries (Pull #1715, Pull #1734)
 * Allow unset SERVER_SOFTWARE in App Engine (Pull #1704, Issue #1470)
 * Remove TLS 1.3 support in SecureTransport (Pull #1703)

Not sure about the wording, but they are user-visible changes. Well, the SecureTransport change is not really visible, but we advertised TLS 1.3 support for all TLS backends in the past, and it's no longer there.

**Comment by sethmlarson** [comment]
You're right, I'll add all those to the changelog! Thanks :)

**Comment by sethmlarson** [comment]
@pquentin When you get a second to gloss over my addition that'd be great.

**Comment by sethmlarson** [comment]
:tada: Will be uploading the release shortly.

**Pull request merged**
