### PR TITLE
Add type hints to test.with_dummyserver.test_poolmanager

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks!

**Comment by pquentin** [comment]
I opened a GitHub support issue (https://support.github.com/ticket/personal/0/1315151) to get help with the required checks, let's avoid touching this until we get an answer. For reference, the current status:

ksnip_20210917-105311

**Review by bluetech — APPROVED** [review]
Great progress, LGTM!

**Review by sethmlarson — APPROVED** [review]
Now that GitHub has gotten back to us we can merge this one.

**Pull request merged**
