### PR TITLE
Add a test for using HTTPHeaderDict with PoolManager(headers)

### PR DESCRIPTION
**Pull request by bluetech**
Add a simple test for `HTTPHeaderDict` in conjunction with `PoolManager`, and the `**headers` syntax (see https://github.com/urllib3/urllib3/issues/2254#issuecomment-860777164).

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks!

**Review by pquentin — APPROVED** [review]
The coverage issue is not caused by the change as it only adds a test.

Are you interested in doing the breaking change suggested in #2254?

**Comment by bluetech** [comment]
Thanks for reviewing @pquentin.

> Are you interested in doing the breaking change suggested in #2254?

I don't think a breaking change there would be acceptable -- it would be silent and have a significant effect. I started trying to add the `extra_headers` solution but it would require some cleanups before it could be done properly.

**Comment by sethmlarson** [comment]
@bluetech [This issue](https://github.com/urllib3/urllib3/issues/2242) is related to this PR as well, basically it's `HTTPHeaderDict` all the way down so we can support duplicate headers without making it a comma.

**Pull request merged**
