### PR TITLE
Improve testing for IPv6 scoped addresses support

### PR DESCRIPTION
**Pull request by delroth**
(A lot) more context in #1641 which ended up motivating this PR. I was thinking of also adding an e2e test checking that opening a connection to 'http://[a::b%iface]' flows properly all the way to create_connection or even socket.socket.connect, but I couldn't find anything similar in the codebase at this point. Instead, the two main parts that could break get tested separately: host extraction for an IPv6 scoped address (as well as normalization), and actually using the zone ID on the "backend" side (GAI/connect).

```
$ pre-commit run --all-files
pyupgrade................................................................Passed
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed

$ pytest test/test_util.py
======================================== test session starts ========================================
platform linux -- Python 3.7.13, pytest-7.0.0, pluggy-1.0.0
rootdir: /home/delroth/work/urllib3/zoneid/urllib3, configfile: setup.cfg
plugins: flaky-3.7.0, timeout-2.1.0, freezegun-0.4.2
collected 330 items

test/test_util.py ........................................................................... [ 22%]
............................................................................................. [ 50%]
.....................................................................s...s................... [ 79%]
.....................................................................                         [100%]

================================== 328 passed, 2 skipped in 0.58s ===================================
```

### CODE REVIEW

**Comment by sethmlarson** [comment]
Thanks for creating this PR @delroth!

I think an E2E test would do a lot of good in this case since there are so many moving parts. If you're looking for a home for the test, maybe [test_poolmanager.py](https://github.com/urllib3/urllib3/blob/main/test/test_poolmanager.py) is a good place?

It'd also be good to backport these tests to the `1.26.x` branch and in the process figure out if the behavior is as expected on that release stream as well.

**Comment by delroth** [comment]
Gave a basic e2e test a shot in 51a1260, let me know if that's roughly what you were thinking about as well.

Regarding backport, I made a branch rebased on 1.26.x, see https://github.com/urllib3/urllib3/compare/1.26.x...delroth:zoneid-1.26.x . The tests pass as expected. I'm not sure what process you follow for backports, I can send the backports as a PR once we've merged this into main if that's fine with you.

**Review by sethmlarson — APPROVED** [review]
This looks great, thanks for adding tests and all your analysis! :rocket: For the backport you can open a PR with these changes and we'll get it merged.

**Comment by sethmlarson** [comment]
Merged, @delroth once you backport this PR you can submit an expense to Open Collective. Let me know if you have questions on that process :)

**Pull request merged**
