### PR TITLE
SSL session reuse support through pyOpenSSL

### PR DESCRIPTION
**Pull request by xnulinu**
Added feature to support SSL resume through pyOpenSSL. The more discussion can be found at 
https://github.com/shazow/urllib3/issues/590

### CODE REVIEW

**Comment by t-8ch** [comment]
`Connection.get_session()` has only been introduced in pyopenssl 0.14, so this will break in older versions.

**Comment by shazow** [comment]
Mmm. Would be nice to add support but it must degrade gracefully.

**Comment by xnulinu** [comment]
@shazow  @t-8ch 

Thanks for the feedback. I was thinking about the compatibility issues with older version of pyOpenSSL. Can someone point me the better way to check method existence so that I can integrate in the code.

**Comment by t-8ch** [comment]
@xnulinu I just began to wonder if this really brings us very much, as we already have connection pooling, which also reuses the established connections.

Otherwise we should also respect the used port in the cache.

**Comment by shazow** [comment]
You can do something like...

```python
if hasattr(someobj, 'somenewmethod'):
    do new stuff
```

If you need to do that check in different places, it might be better to just set a variable somewhere, like:

```python
self.has_ssl_resume = hasattr(someobj, 'somenewmethod')
```

**Comment by shazow** [comment]
> I just began to wonder if this really brings us very much, as we already have connection pooling, which also reuses the established connections.

Good point. I guess this lets us re-use SSL sessions across a pool of connections, which is not the default behaviour anyways (default pool size is 1). Maybe this should be something that needs to be enabled explicitly?

**Comment by xnulinu** [comment]
@t-8ch 
SSL resume is more about avoiding full SSL handshake each time a client request a resources. This will save complete round-trip time and avoids the costlier part of full SSL handshake.  This feature with the Connection Pool will increase latency and computation time. 

About the used port on the cache, I also think we should use that. I don't know how to retrieve in the pyOpenSSL ssl_wrap_socket method.

**Comment by shazow** [comment]
Maybe a better place to cache SSL contexts would be within the HTTPSConnectionPool instances?

**Comment by t-8ch** [comment]
@xnulinu You can do `sock.getpeername()`

**Comment by xnulinu** [comment]
@t-8ch 

that will do it.

**Comment by shazow** [comment]
Shouldn't need to get the host or peer if the context is saved in the HTTPSConnectionPool right after the first socket is created.

**Comment by xnulinu** [comment]
@shazow 

If we do on the HTTPSConnectionPool, how we are going to retrieve the context in the ssl_wrap_socket  method. Are you thinking to do the method change or use some setattr magic.

**Comment by shazow** [comment]
The `WrappedSocket` that our pyopenssl module returns has the connection context fromwhich we can get the session. Could add a `ssl_context_session(connection)` helper into `util/ssl_.py` which attempts to extract a re-usable session from a connection, otherwise returning `None` (right now only supporting the pyopenssl thing, but ultimately maybe py3+ will get support too?).

Then in `HTTPSConnectionPool` can attempt to re-use an SSL session if it has one, else just keep doing what it normally does (and save the next SSL session it gets).

**Comment by t-8ch** [comment]
Are connectionpools keyed by DNS names? If so we have to use `getpeername` else we may reuse a session and the DNS name may resolve to a different host with which we can't resume the session initiated by the other host.
This Means we have to query the cache after we created the socket.
Or should we prefer those IP addresses of DNS names we already have sessions for?

**Comment by shazow** [comment]
You're right, the PoolManager is keying on the (scheme, hostname, port) right now. Maybe it shouldn't be, but then we'd have to resolve the host earlier than later. :/

**Comment by t-8ch** [comment]
I think the PoolManager should be allowed to. But the SessionCache can't.

**Comment by shazow** [comment]
While I'd love to re-use our pooling logic whenever possible (rather than re-implementing it in various islands). For now, since this only applies to a sub-version of pyopenssl, we can keep it isolated.

**Comment by t-8ch** [comment]
OTOH, different connectionpools to the same endpoint may very well have different SSL configurations (in our case SSL versions). So caching sessions globally can lead to inconsistencies.

And: Can we reuse a session while it is still in use by another connection? Which will easily, as we keep connections open.

**Comment by jonparrott** [comment]
Thank you for creating this pull request, unfortunately, for one reason or
another it has become stale. We are declaring PR bankruptcy (see #1370) to
better focus our limited volunteer resources. If you still think this PR is
relevant and useful, please comment and let us know!

**Comment by devshorts** [comment]
@theacodes I'd definitely still like this PR to come to fruition. Being able to re-use ssl tickets is a big performance booster when dealing with many requests.

**Pull request closed without merging**
