### PR TITLE
Update contributing doc

### PR DESCRIPTION
**Pull request by RatanShreshtha**
Update contributing doc as Makefile is not used.

### CODE REVIEW

**Comment by sethmlarson** [comment]
(Looks like an unrelated test is failing, I'll submit a fix and we can merge this)

**Comment by RatanShreshtha** [comment]
@sethmlarson  I don't understand why tests are failing

**Comment by sethmlarson** [comment]
Travis is putting `TRAVIS_INFRA=unknown` on some of our jobs despite it almost certainly being `gce` because it also has the dotted FQDN problem.

**Comment by RatanShreshtha** [comment]
CI is passing now

**Comment by sethmlarson** [comment]
Thanks @RatanShreshtha!

**Comment by RatanShreshtha** [comment]
Thanks for the merge

**Pull request merged**
