### PR TITLE
Drop Python 3.5

### PR DESCRIPTION
**Pull request by hramezani**
Fixes  https://github.com/urllib3/urllib3/issues/1997

### CODE REVIEW

**Comment by hramezani** [comment]
Should we remove `pypy3.5-6.0` from `.travis.yml`?

**Review by sethmlarson — CHANGES_REQUESTED** [review]
All the changes in this PR look good, thank you for them. Two things:

- We can't merge this into `master` until we cut a `v1.26.x` release stream
- I think it'd be best to remove Python 2.7 first, then remove Python 3.5 second so we can drop all the conditional (`sys.version_info < (3, 5)`) sections entirely rather than increment them to `< (3, 6)` which might make them tougher to find in the future.

For now we can have this PR here waiting for that to happen if you'd like :)

**Comment by pquentin** [comment]
> Should we remove pypy3.5-6.0 from .travis.yml?

We should actually use a newer PyPy that supports Python 3.6 instead, see https://github.com/urllib3/urllib3/pull/2013

**Comment by pquentin** [comment]
@hramezani Sorry, we ended up merging #2044 instead who had better timing.

The good news is that we have now a clear cut list of issues to fix before we can release 2.0: https://github.com/urllib3/urllib3/issues?q=is%3Aopen+is%3Aissue+label%3A%22Breaking+Change%22+milestone%3Av2.0

**Pull request closed without merging**
