### PR TITLE
Remove more Python 2.6 code

### PR DESCRIPTION
**Pull request by pquentin**
This also fixes an installation error of gcp-devrel-py-tools==0.0.15, see https://github.com/GoogleCloudPlatform/python-repo-tools/issues/23 for details. I can separate that in two PRs if needed.

### CODE REVIEW

**Comment by pquentin** [comment]
Added two possible Windows errors in test_client_no_intermediate, per https://github.com/urllib3/urllib3/issues/1422#issuecomment-413491190.

I will also need to investigate the lower coverage.

**Comment by SethMichaelLarson** [comment]
Thanks @pquentin! :tada:

**Comment by speedplane** [comment]
This broke urllib3 on Google App Engine, which also doesn't have _tunnel_host in its implementation of httplib. The `if getattr(self, '_tunnel_host', None):` part should go back in.

**Comment by pquentin** [comment]
Oh. Can you please open a pull request to fix that? Thanks!

**Pull request merged**
