### PR TITLE
Fix HTTP/1.1 debug log

### PR DESCRIPTION
**Pull request by pquentin**
Thanks @nateprewitt for the report.

### CODE REVIEW

**Review by sethmlarson — DISMISSED** [review]
LGTM, thanks!

**Comment by sethmlarson** [comment]
Ah, do we need a changelog for this since it's a bugfix?

**Comment by Pierre-Sassoulas** [comment]
Fun fact, this bug fix broke ``pytest-vcr`` and ``vcrpy``, they now crash on existing cassette with the following error message `'VCRHTTPResponse' object has no attribute 'version_string'`. You'll probably guess what xkcd I'm going to link [here](https://xkcd.com/1172/)

**Comment by Pierre-Sassoulas** [comment]
Didn't look too much into it, but downgrading to urllib < 2.3 works and this was the only occurrence of 'version_string' in the whole diff from 2.2.3..2.3.0, so I suppose it's a reasonable guess that it's the "culprit". (I'm not saying that urllib did anything wrong here, just sharing the 'fun' result of 1 hour of debug 😄)

**Pull request merged**
