### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### shazow/urllib3 now has a Chat Room on Gitter

@haikuginger has just created a chat room. You can visit it here: [https://gitter.im/python-urllib3/Lobby](https://gitter.im/python-urllib3/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/python-urllib3/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by haikuginger** [comment]
Leaving this open while we wait to see if Gitter works as a place for us in general.

**Comment by SethMichaelLarson** [comment]
It looks like we've been using Gitter quite a lot, I'd like to cement it's place in the README.

**Comment by jonparrott** [comment]
Ugh this is horribly out of date. I wonder if I close it will it open a fresh one?

**Comment by SethMichaelLarson** [comment]
I don't think so, it's not like pyup fortunately. This is an offer some may want to refuse! ;)

**Comment by jonparrott** [comment]
Aw, is anyone willing to do this manually? (Or I can tomorrow)

**Comment by SethMichaelLarson** [comment]
Done

**Pull request closed without merging**
