### PR TITLE
Fix TestBrokenPipe on macOS

### PR DESCRIPTION
**Pull request by zawan-ila**
Fixes [2770](https://github.com/urllib3/urllib3/issues/2770)

### CODE REVIEW

**Comment by sethmlarson** [comment]
@zawan-ila This doesn't have an explanation for why this PR is correct, I don't think we should be silencing exceptions we don't understand. Do you know why this issue is occurring?

**Comment by zawan-ila** [comment]
@sethmlarson The reason that this is occuring is essentially the same as the one that we "catch" `EPROTOTYPE` here for. Remembrances from the past [here](https://github.com/urllib3/urllib3/pull/1524/commits/567a8f4b265b216fc78f92d2af9dc3caf5f4b878) and [here](https://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/)

What's happened since then is that Apple changed some of their code and some of the code paths that resulted in the `EPROTOTYPE` mentioned above now result in the setting of `ECONNRESET`. In particular, note the difference in the if block between the [old version](https://github.com/apple-oss-distributions/xnu/blob/rel/xnu-7195/bsd/netinet/tcp_usrreq.c#L1020C1-L1024) and the [new one](https://github.com/apple-oss-distributions/xnu/blob/main/bsd/netinet/tcp_usrreq.c#L1164-L1168). In fact, I don't think we need the special "catch" for `EPROTOTYPE` anymore.

**Review by sethmlarson — APPROVED** [review]
Thanks for the explanation! LGTM

**Comment by pquentin** [comment]
Since we closed https://github.com/urllib3/urllib3/issues/2770, can we bump CI to macos-12?

**Comment by sethmlarson** [comment]
@pquentin I believe we can! :)

**Pull request merged**
