### PR TITLE
Test on PyPy3

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by thedrow** [comment]
FYI This was resolved in PyPy.

**Comment by shazow** [comment]
Ooo. @frewsxcv Wanna rebase this so it re-runs on the latest master?

**Comment by frewsxcv** [comment]
Sure, one sec

**Comment by frewsxcv** [comment]
It looks like the bug was fixed in November 2014, but the latest PyPy stable is from a couple months before that, so it's still failing.

**Comment by shazow** [comment]
Mmm funsies. Well let's hang on until it's running on travisci.

**Comment by t-8ch** [comment]
We could also add:

```yaml
matrix:
  allow_failures:
    - python: pypy3
```

**Comment by frewsxcv** [comment]
> allow_failures:

I won't speak for the project since I'm not part of the leadership, but I disagree with that. The tests are going to fail every single time on PyPy 3 until a new version is released, so there's not really much of a rush getting this merged.

**Comment by shazow** [comment]
I'd be happier if someone wants to keep a fork going with travisci building against pypy3 and let me know when it's working. ;)

**Comment by frewsxcv** [comment]
Coincidentally, it looks like the PyPy 2.5 release branch [was created a few days ago](https://bitbucket.org/pypy/pypy/commits/branch/release-2.5.x). I just asked in `#pypy` on Freenode and they said there will likely be a new release this week.

**Comment by frewsxcv** [comment]
PyPy 2.5 has been released http://morepypy.blogspot.com/2015/02/pypy-250-released.html

Now we just have to wait for Travis...

**Comment by kevinburke** [comment]
Any update here?

**Comment by frewsxcv** [comment]
Just reran the tests. Looks like Travis is still running PyPy 2.4 :(

**Comment by sigmavirus24** [comment]
@Lukasa can you re-run these tests?

**Comment by frewsxcv** [comment]
Still running PyPy 2.4 :-/ 

https://travis-ci.org/shazow/urllib3/jobs/62703110

**Comment by sigmavirus24** [comment]
Well that's extraordinarily disappointing.

**Comment by t-8ch** [comment]
Afaik pypy3 2.5.0 is not even released yet.

**Comment by frewsxcv** [comment]
> Afaik pypy3 2.5.0 is not even released yet.

https://github.com/shazow/urllib3/pull/498#issuecomment-72762712

**Comment by t-8ch** [comment]
That was pypy2

**Comment by frewsxcv** [comment]
> That was pypy2

You're right, sorry about that. I forgot that PyPy 3 and PyPy have their own versioning and release cycles. So I guess we're just waiting for a new version of PyPy 3 to be released? The latest tag for PyPy 3 appears to be [pypy3-release-2.4.0](https://bitbucket.org/pypy/pypy/commits/tag/pypy3-release-2.4.0) from October of 2014.

**Comment by t-8ch** [comment]
No need to be sorry!
I made this mistake at least 4 times :-)

**Comment by jonparrott** [comment]
Thank you for creating this pull request, unfortunately, for one reason or
another it has become stale. We are declaring PR bankruptcy (see #1370) to
better focus our limited volunteer resources. If you still think this PR is
relevant and useful, please comment and let us know!

**Pull request closed without merging**
