### PR TITLE
Release 1.26.7

### PR DESCRIPTION
**Pull request by sethmlarson**
* [x] See if all tests, including integration, pass
  * Botocore dropped support for Python 2.7 in July, expected to fail here.
* [x] Get the release pull request approved by a [CODEOWNER](https://github.com/urllib3/urllib3/blob/main/.github/CODEOWNERS)
* [x] Squash merge the release pull request with message "`Release <VERSION>`"
* [ ] Tag with X.Y.Z, push tag on urllib3/urllib3 (not on your fork, update `<REMOTE>` accordingly)
  * Notice that the `<VERSION>` shouldn't have a `v` prefix (Use `1.26.6` instead of `v.1.26.6`)
  * ```
    git tag -a '<VERSION>' -m 'Release: <VERSION>'
    git push <REMOTE> --tags
    ```
* [ ]  Push to PyPI
  * ```
    cd /tmp
    git clone ssh://git@github.com/urllib3/urllib3
    cd urllib3
    git checkout <TAG/VERSION>
    python -m venv
    source venv/bin/activate
    python -m pip install -U pip
    python -m pip install -U twine setuptools wheel
    python setup.py sdist bdist_wheel
    
    twine check dist/*
    # Inspect the output to make sure it looks right
    # Check versions, should be 1 wheel 1 sdist
    
    twine upload dist/*
    ```
* [ ]  Grab sdist and wheel from PyPI to attach to GitHub release
* [ ]  Announce on:
  * [ ]  GitHub releases
  * [ ]  Twitter
  * [ ]  Discord
  * [ ]  OpenCollective
  * [ ]  GitCoin Grants
* [ ]  Update Tidelift metadata

### CODE REVIEW

**Comment by sethmlarson** [comment]
Contacted @nateprewitt about the failure in https://github.com/urllib3/urllib3/pull/2422/checks?check_run_id=3676748920. Looks like [v1.21.0 dropped Python 2.7](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#1210) which might mean we need to pull that tag for downstream tests of boto+2.7.

**Comment by pquentin** [comment]
Can we just stop worrying about botocore on 2.7?

**Review by pquentin — DISMISSED** [review]

**Review by nateprewitt — DISMISSED** [review]
Yep, Botocore dropped support for Python 2.7 in July. It should be fine to drop that test.

**Comment by sethmlarson** [comment]
Captured a todo issue for dropping these integration tests on 1.26.x: https://github.com/urllib3/urllib3/issues/2423

**Review by pquentin — APPROVED** [review]

**Pull request merged**
