### PR TITLE
Stop skipping SecureTransport tests

### PR DESCRIPTION
**Pull request by pquentin**
They're failing on macOS 10.15, which means I can't run them locally,
which is why I skip them. Sorry about that.

### CODE REVIEW

**Comment by sethmlarson** [comment]
No problem! This is why visual indicators for test run differences are useful :P

**Comment by pquentin** [comment]
Sigh, and obviously the `ca_certs=os.devnull` hack introduced in #1812 works fine for the standard library and PyOpenSSL but breaks on macOS. I plan to try to fix that for a few days, but if I don't find enough time or otherwise fail, I'll revert #1812 and merge this one.

> This is why visual indicators for test run differences are useful :P

Do you mean the codecov coverage? Yeah, that would help, but not in this case. The problem here is that SecureTransport is a "contrib" module and is not part of coverage computations.

(I'm considering dropping codecov and instead make sure each Python 3 run is at 100%, by enforcing it with `coverage` and ignoring a few currently covered lines. It would be way more reliable.)

**Comment by sethmlarson** [comment]
I mean more of a "here's what tests ran and for which config and how that differs from the master branch". We don't get that with Codecov or Travis or any CI unfortunately.

**Comment by sethmlarson** [comment]
Looks like there is an issue that was introduced in #1812, could you take a look @pquentin?

**Comment by pquentin** [comment]
Just got the following unrelated error in `test/contrib/test_securetransport.py::TestSSL::test_ssl_read_timeout` at https://travis-ci.org/github/urllib3/urllib3/jobs/665716556.

```
Traceback (most recent call last):
  File "/Users/travis/build/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/Users/travis/build/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/urllib3/response.py", line 503, in read
    data = self._fp.read() if not fp_closed else b""
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 610, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(3 bytes read, 7 more expected)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/build/urllib3/urllib3/test/with_dummyserver/test_socketlevel.py", line 1209, in test_ssl_read_timeout
    response.read()
  File "/Users/travis/build/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/urllib3/response.py", line 503, in read
    data = self._fp.read() if not fp_closed else b""
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/travis/build/urllib3/urllib3/.nox/test-3-8/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(3 bytes read, 7 more expected)', IncompleteRead(3 bytes read, 7 more expected))
```

Cycling the pull request.

**Comment by pquentin** [comment]
Closing/reopening did not restart the builds. Trying again...

**Comment by pquentin** [comment]
Okay, so the 3.8 failure appears to be real: there's another one at https://travis-ci.org/github/urllib3/urllib3/jobs/665746917

**Comment by pquentin** [comment]
So the failing test never worked on Python 3.8 + SecureTransport, since the commit who added it to the SecureTransport tests is the same commit that disabled SecureTransport tests. And at the time, I was using Python 3.7 for development.

It could be interesting to figure out the issue, but for now let's disable the test: it's more important to have working SecureTransport tests than to figure out why this new one is failing.

Please take another look.

**Pull request merged**
