### PR TITLE
Release 1.26.14

### PR DESCRIPTION
**Pull request by pquentin**
* [x]  See if all tests, including integration, pass
* [x]  Get the release pull request approved by a [CODEOWNER](https://github.com/urllib3/urllib3/blob/main/.github/CODEOWNERS)
* [ ]  Squash merge the release pull request with message "`Release <VERSION>`"
* [ ]  Tag with X.Y.Z, push tag on urllib3/urllib3 (not on your fork, update `<REMOTE>` accordingly)
  * Notice that the `<VERSION>` shouldn't have a `v` prefix (Use `1.26.6` instead of `v.1.26.6`)
  * ```
    git tag -s -a '<VERSION>' -m 'Release: <VERSION>'
    git push <REMOTE> --tags
    ```
* [ ]  Execute the `publish` GitHub workflow. This requires a review from a maintainer.
* [ ]  Ensure that all expected artifacts are added to the new GitHub release. Should
       be one `.whl`, one `.tar.gz`, and one `urllib3.intoto.jsonl`. Update the GitHub
       release to have the content of the release's changelog.
* [ ]  Announce on:
  * [ ]  Twitter
  * [ ]  Discord
  * [ ]  OpenCollective
* [ ]  Update Tidelift metadata
* [ ]  If this was a 1.26.x release, add changelog to the `main` branch

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Comment by sethmlarson** [comment]
@pquentin Shall we make the release day either today or tomorrow?

**Comment by pquentin** [comment]
Either works, but I won't be able to help more today myself unfortunately. Tomorrow I'll have the bandwidth to merge, push the tags if I have the permission, etc.

**Review by sethmlarson — APPROVED** [review]
LGTM

**Pull request merged**
