### PR TITLE
Update the version of gcp-devrel-py-tools to fix App Engine builds

### LINKED ISSUE #1400: Google App Engine tests not working on CI
Saw this in a different PR with unrelated changes: https://travis-ci.org/urllib3/urllib3/jobs/393557123#L552
Has GAE testbed changed, maybe we need to update our scripts.

Assigning this to you Thea as our GAE champion.

### PR DESCRIPTION
**Pull request by theacodes**
Fixes #1400

### CODE REVIEW

**Comment by pquentin** [comment]
The build now fails because of a SecureTransport failure on macOS with Python 3.7. I guess retrying the build could work?

**Comment by theacodes** [comment]
iirc we're holding on to that for the benefit of pip.

**Comment by pquentin** [comment]
@theacodes pip 10 dropped support for Python 2.6, see https://pip.readthedocs.io/en/stable/news/#b1-2018-03-31

**Comment by theacodes** [comment]
Interesting

**Pull request merged**
