### PR TITLE
Try removing Codecov

### PR DESCRIPTION
**Pull request by sethmlarson**
From https://hynek.me/til/ditch-codecov-python, let's try to get rid of Codecov.

### CODE REVIEW

**Comment by nedbat** [comment]
This [works if you specify paths to combine](https://github.com/nedbat/urllib3/actions/runs/1567764239):
```
[paths]
source =
    src/urllib3
    */urllib3
    *\urllib3
```

TBH, relative_files is still kind of spotty.

**Comment by nedbat** [comment]
I don't understand why this is needed: https://github.com/urllib3/urllib3/pull/2490/files#diff-fad2fa83c042cce646b2c1a0455e9b60c22dd5f105ed8859ce85dcf361c07fbdR11-R13

**Comment by sethmlarson** [comment]
@nedbat Thanks for commenting here, that was my attempt at making `.coverage` files names not collide when uploaded as an artifact to GitHub Actions.

**Comment by nedbat** [comment]
If you use `parallel = True` in the .coveragerc, they will get unique names anyway, so you shouldn't need that.

**Comment by sethmlarson** [comment]
@nedbat Right, I tried implementing without the parallel runs because I wasn't sure if that was messing with `relative_path` somehow but gave up on that train of thought, forgot to remove the random token though!

**Comment by sethmlarson** [comment]
Success! Thanks @nedbat for your help with this!

**Pull request merged**
