### PR TITLE
Add flake8 config file for ignoring black styles linting error.

### PR DESCRIPTION
**Pull request by RatanShreshtha**
Added .flake8 file copied mainly from https://github.com/theacodes/nox/blob/master/.flake8 and removed the # noqa.

### CODE REVIEW

**Comment by haikuginger** [comment]
Could you rebase this specific change on master rather than on the "remove addCleanup" branch? Thanks!

**Comment by RatanShreshtha** [comment]
I have updated the PR.

**Comment by sethmlarson** [comment]
Looks like black is catching a [linting issue](https://travis-ci.org/urllib3/urllib3/jobs/540939860#L375)?

**Comment by pquentin** [comment]
Can we expand the configuration in setup.cfg instead of creating a new file?

**Comment by RatanShreshtha** [comment]
Updated the PR and added the flake8 ignore rules in setup.cfg

**Comment by sethmlarson** [comment]
Thanks for this! :)

**Pull request merged**
