### PR TITLE
:zap: Backport of #2849 - fixed issue with port "0" returning None

### LINKED ISSUE #2850: parse_url with :0 returns port=None
it should return port=0 instead

### PR DESCRIPTION
**Pull request by imkaka**
Closes #2850

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Awesome, thank you! :rocket:

**Comment by sethmlarson** [comment]
@imkaka Can you run `nox -rs format` locally and push the results?

**Comment by imkaka** [comment]
> @imkaka Can you run `nox -rs format` locally and push the results?

Done.

**Review by sethmlarson — APPROVED** [review]
Thank you!

**Pull request merged**
