### PR TITLE
Fix Bug About Chunk Error

### PR DESCRIPTION
**Pull request by DeeLMind**
To Fix : requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

### CODE REVIEW

**Comment by sethmlarson** [comment]
Is this related to this thread: https://github.com/urllib3/urllib3/issues/1516

**Comment by sethmlarson** [comment]
This fix has landed in master already. Thank you for this fix.

**Comment by sethmlarson** [comment]
I mistakenly closed this. My bad.

**Comment by DeeLMind** [comment]
It does't matter , thank you for your reply , I am newer

**Comment by mdeuts** [comment]
Dear @sethmlarson 
This fix is absent in master...
Any chance to re-examine its necessity please?
Many thanks!!

**Comment by pquentin** [comment]
@mdeuts The fix we landed is https://github.com/urllib3/urllib3/pull/1888 to report exactly what the issue is: it's a server-side issue and the servers reporting incorrect chunks should be fixed.

**Pull request closed without merging**
