### PR TITLE
Formatted the urllib3 code using black.

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by haikuginger** [comment]
> Skimmed through the changes, lookin' good. We have 7 new # noqa's, not super clear to me what those lines are doing badly, but maybe worth rewriting them later?

Three string literals that are just too long for their lines according to flake8, and three places where flake8 doesn't like whitespace after a colon inside a slice parameter.

**Comment by theacodes** [comment]
Let's just add a .flake8 file? Steal Nox's?
https://github.com/theacodes/nox/blob/master/.flake8

**Comment by haikuginger** [comment]
Thank you for your contribution, @RatanShreshtha!

**Comment by RatanShreshtha** [comment]
thanks for the merge

**Pull request merged**
