### PR TITLE
Move urllib3 to src/urllib3

### PR DESCRIPTION
**Pull request by pquentin**
When tests are outside the main package, [tox recommends putting the main package under an 'src' directory](https://docs.pytest.org/en/latest/goodpractices.html) to ensure that the installed package is tested, not the source. This layout has [other benefits](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure), too.

We actually ran into this issue in the [async support branch](https://github.com/urllib3/urllib3/pull/1335): the installation step adds the sync version by removing async/await keywords, so that's the only way to make tox work in that branch.

cc @njsmith

### CODE REVIEW

**Comment by pquentin** [comment]
SecureTransport failure on Python 3.7: https://travis-ci.org/urllib3/urllib3/jobs/399539365, trying again.

**Comment by pquentin** [comment]
Now a TestHTTPS.test_client_no_intermediate failure on Python 2.6 on macOS: https://travis-ci.org/urllib3/urllib3/jobs/399564364, trying again.

**Comment by sigmavirus24** [comment]
I'm generally in favor of this.... once tests pass of course :)

**Comment by pquentin** [comment]
Now a TestHTTPS.test_client_no_intermediate failure on Python 3.4 on Windows: https://ci.appveyor.com/project/urllib3/urllib3/build/1.0.176/job/tenbr6b2hj4crfbg. Trying again!

**Comment by pquentin** [comment]
Yay, all tests pass! I've seen those failures before: I don't think they're related to this change.

**Comment by pquentin** [comment]
Oh, no, they don't actually pass. [This time](https://travis-ci.org/urllib3/urllib3/builds/399587342) it's three macOS failures, two TestHTTPS.test_client_no_intermediate and one TestSocketClosing.test_delayed_body_read_timeout.

**Comment by pquentin** [comment]
Sorry for the noise, but I think it's useful to know what tests are flaky? Or maybe I should focus on fixing test_client_no_intermediate.

The latest failure? TestHTTPS.test_client_no_intermediate on macOS and Python 3.7: https://travis-ci.org/urllib3/urllib3/jobs/399606514.

**Pull request merged**
