### PR TITLE
Configure dependabot to set the "Skip Changelog" label to PRs

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Review by pquentin — DISMISSED** [review]
Thanks! LGTM.

**Review by sethmlarson — DISMISSED** [review]
Great idea, thanks Illia!

**Comment by illia-v** [comment]
I found out that the defined labels override the default ones, so I added the latter to the list too

**Comment by sethmlarson** [comment]
Tbh I'm actually okay if we don't have those extra labels, I haven't used them for anything productive. Does anyone else find them useful?

**Comment by illia-v** [comment]
> Tbh I'm actually okay if we don't have those extra labels, I haven't used them for anything productive. Does anyone else find them useful?

Not much, but color of the `dependencies` label helps me distinguish dependabot's PRs from others

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
