### PR TITLE
Remove spurious TypeError from exception chain also for BaseException.

### LINKED ISSUE #1636: Spurious TypeError if BaseException occurs during getresponse()
This issue is a repeat of #861, but for exceptions that derive from `BaseException` and not `Exception`.

Specifically, if an `Exception` gets raised from `conn.getresponse()` in this line of code: https://github.com/urllib3/urllib3/blob/728d9244665ef5b03103cb74d7b409ebe4f23b43/src/urllib3/connectionpool.py#L411

then `urllib3` calls `raise from None` to remove the spurious `TypeError` from the exception chain: https://github.com/urllib3/urllib3/blob/728d9244665ef5b03103cb74d7b409ebe4f23b43/src/urllib3/connectionpool.py#L405-L415

However, if a `BaseException` like `KeyboardInterrupt` or `SystemExit` is raised during the call to `conn.getresponse()`, then the `TypeError` _isn't_ removed. This is because the try-except only catches and re-raises `Exception` and not `BaseException`. As mentioned in the original #861, seeing the spurious `TypeError` makes it look like there is bug e.g. in the error handling that occurs while the program exits. The `BaseException` can occur e.g. if a request is taking a long time and the application is terminated from another process.

The fix is to change `Exception` to `BaseException` in this line of code: https://github.com/urllib3/urllib3/blob/728d9244665ef5b03103cb74d7b409ebe4f23b43/src/urllib3/connectionpool.py#L412

I would file a PR, but I'm not sure I'd have time to craft a test. I note, though, that the original PR #861 didn't have a test.

### PR DESCRIPTION
**Pull request by cjerdonek**
Fixes #1636: https://github.com/urllib3/urllib3/issues/1636

### CODE REVIEW

**Comment by sethmlarson** [comment]
What exception in particular were you hitting this case with? `KeyboardInterrupt`?

**Comment by cjerdonek** [comment]
In my case it was `SystemExit`. It was a long-running request, and the process was timed out / terminated by an outside process.

**Comment by cjerdonek** [comment]
Thanks!

**Comment by sethmlarson** [comment]
Thank you very much @cjerdonek! If you have more time there are plenty of other issues available to be taken up. :)

**Pull request merged**
