### PR TITLE
Generate certificate directory at runtime

### PR DESCRIPTION
**Pull request by pquentin**
Instead of storing it in git.

Done as part of #1705

### CODE REVIEW

**Comment by pquentin** [comment]
I just found out about http://doc.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture, so I pushed a new commit here

**Comment by pquentin** [comment]
This pull request includes commits from #1724, so please review/merge #1724 first so that we have a record of it in the history.

**Comment by pquentin** [comment]
This is also ready for review. :) But again, #1724 should be merged first.

**Comment by sethmlarson** [comment]
Is there a conflict on this PR? Do we need these changes still?

**Comment by pquentin** [comment]
This was merged as part of #1725. Thanks! Closing.

**Pull request closed without merging**
