### PR TITLE
[1.26] Remove Python 3.5 support

### PR DESCRIPTION
**Pull request by chetanugale**
Fixes : https://github.com/urllib3/urllib3/issues/2449

### CODE REVIEW

**Comment by sethmlarson** [comment]
@chetanugale We're waiting to merge this as the 1.26.x branch is in an almost releaseable state. Don't want to introduce this change quite yet. Thanks for your patience.

**Comment by pquentin** [comment]
The other problem is that coverage is reporting nonsense, and we really need this to make sure we haven't forgotten anything.

**Comment by hramezani** [comment]
@pquentin can we merge this? is there anything left?

**Comment by sethmlarson** [comment]
@hramezani We shouldn't merge yet, want to get 1.26.8 released first after the HTTPS proxy PR lands.

**Comment by pquentin** [comment]
Restarting after `FAILED test/contrib/test_pyopenssl.py::TestSSL::test_ssl_custom_validation_failure_terminates` on Windows 3.10.

**Comment by pquentin** [comment]
@sethmlarson this is ready for another round of review!

- Coverage is actually 100%: the source of truth is now the coverage GitHub Actions check, not Codecov
- I had to fix unrelated black breakage and took the opportunity to upgrade it. Should I do this in a separate PR?
- Before mere mortals can merge, the 3.5 checks need to be disabled in 1.26.x

**Comment by sethmlarson** [comment]
Thanks @pquentin for getting this into a reviewable state!

> Coverage is actually 100%: the source of truth is now the coverage GitHub Actions check, not Codecov

> I had to fix unrelated black breakage and took the opportunity to upgrade it. Should I do this in a separate PR?

Could you do this in a separate PR? (Thank you!)

> Before mere mortals can merge, the 3.5 checks need to be disabled in 1.26.x

I'll remove this right now!

**Review by sethmlarson — APPROVED** [review]
This diff now looks much better, thanks again @chetanugale for opening this and @pquentin for pushing this over the finish line! :tada:

**Comment by pquentin** [comment]
We got another `test_ssl_custom_validation_failure_terminates` failure on Windows 3.10:

```
____________ TestSSL.test_ssl_custom_validation_failure_terminates ____________
Traceback (most recent call last):
  File "D:\a\urllib3\urllib3\test\with_dummyserver\test_socketlevel.py", line 1499, in test_ssl_custom_validation_failure_terminates
    assert server_closed.wait(LONG_TIMEOUT), "The socket was not terminated"
AssertionError: The socket was not terminated
assert False
 +  where False = <bound method Event.wait of <threading.Event object at 0x000002A5D777CC10>>(0.5)
 +    where <bound method Event.wait of <threading.Event object at 0x000002A5D777CC10>> = <threading.Event object at 0x000002A5D777CC10>.wait
```

Restarting that job.

**Pull request merged**
