### PR TITLE
Move Windows CI to Actions

### PR DESCRIPTION
**Pull request by hodbn**
#### Add Windows to Actions
Changed the workflow a bit to allow running all steps on both Windows/macOS.

#### Remove AppVeyor
Removed AppVeyor's configuration and badge. Instead, added CI workflow badge and marked 3.9-dev testing as experimental (failure won't affect status and badge).

#### TODO
Optimize workflow for speed.

### CODE REVIEW

**Review by sethmlarson — DISMISSED** [review]
LGTM! Going to squash this and backport it to `1.25-series` and then I can uncheck the AppVeyor CI status
Would like @pquentin's review first before merging :)

**Review by pquentin — CHANGES_REQUESTED** [review]
Can you please remove the `_appveyor` directory?

**Comment by hodbn** [comment]
> 
> 
> Can you please remove the `_appveyor` directory?

I knew I missed something :) Done

**Review by pquentin — APPROVED** [review]
Thanks! It's unusual to order by Python version instead of by OS, but it probably makes more sense this way!

Goodbye AppVeyor, you served us well.

**Review by sethmlarson — APPROVED** [review]
Will squash when I'm home. Goodbye AppVeyor!

**Review by shazow — APPROVED** [review]
:custard: !

**Pull request merged**
