### PR TITLE
Change deprecation warnings to explicitly mention v2.1.0 for removals

### PR DESCRIPTION
**Pull request by sethmlarson**
Plan between @pquentin and I is to release 2.0.0 pre-releases early next week, do a bunch of hardening and integration testing against existing packages, and then release 2.1.0 will the actual removals of deprecated features sometime in the summer of 2023.

Closes https://github.com/urllib3/urllib3/issues/2781

### CODE REVIEW

**Comment by sethmlarson** [comment]
Planning on reverting the changes to the release schedule since it's covered in the release candidate PR.

**Review by pquentin — CHANGES_REQUESTED** [review]
Thanks! There are places in docs/ and changelog/ where we still mention a "future" release. Grepping for future will find them. Can you please update them too? Also, yes, a deprecation page would be super useful.

**Comment by sethmlarson** [comment]
@pquentin I've removed the occurrences in `docs/`. The ones in `changelog/` are removed in this PR: https://github.com/urllib3/urllib3/pull/2795

**Review by pquentin — APPROVED** [review]
Thanks! Looks good to me.

**Pull request merged**
