### PR TITLE
Don't log a warning on content-type: multipart/* responses

### LINKED ISSUE #800: Multipart mixed responses generate warnings
If you read a multipart/mixed response, the connectionpool issues a couple of warnings about defects in the message. I'm not sure what the expected, correct behavior is, but these warnings seem spurious.

Stick this perl script somewhere:

```
#!/usr/bin/perl

print "Server: Some Server Name\r\n";
print "Content-Type: multipart/mixed; boundary=36eeb8c4e26d842a\r\n";
print "Content-Length: 178\r\n";
print "\r\n\r\n";
print "--36eeb8c4e26d842a\r\n";
print "Content-Type: text/plain\r\n";
print "\r\n";
print "7\r\n";
print "--36eeb8c4e26d842a\r\n";
print "Content-Type: text/plain\r\n";
print "\r\n";
print "9\r\n";
print "--36eeb8c4e26d842a\r\n";
print "Content-Type: text/plain\r\n";
print "\r\n";
print "11\r\n";
print "--36eeb8c4e26d842a--\r\n";
```

Read it with requests (naturally, you'll have to change the URI to wherever you put the script):

```
import requests, logging

logging.basicConfig(level=logging.WARNING)
logging.getLogger("requests").setLevel(logging.DEBUG)

headers = {'accept': "multipart/mixed"}
r = requests.get("http://localhost:8124/cgi-bin/mpm.pl", headers=headers)

print(r)
```

The following errors are displayed:

```
DEBUG:requests.packages.urllib3.connectionpool:"GET http://localhost:8124/cgi-bin/mpm.pl HTTP/1.1" 200 178
WARNING:requests.packages.urllib3.connectionpool:Failed to parse headers (url=http://localhost:8888/http://localhost:8124/cgi-bin/mpm.pl): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/home/ndw/.virtualenvs/pyapi/lib/python3.4/site-packages/requests-2.8.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 390, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/ndw/.virtualenvs/pyapi/lib/python3.4/site-packages/requests-2.8.0-py3.4.egg/requests/packages/urllib3/util/response.py", line 58, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
requests.packages.urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```

It took me quite a while to work out that they were spurious (because in real life, the server side that is generating the multipart/mixed is more complicated!)

See also kennethreitz/requests#3001
##

### PR DESCRIPTION
**Pull request by badcure**
This is to address the multipart errors that are showing up in urllib. The real fix is upstream, but the goal is to remove the false warnings that are showing up as described in https://github.com/urllib3/urllib3/issues/800 . 

If the exceptions show up, I am simply removing them from the list. The exceptions would only apply if it is processing the body as well. In the urllib3 code path, it only cares about the headers at that point.

Closes #800

### CODE REVIEW

**Comment by badcure** [comment]
Hello @pquentin , wanted to see if you had time to look over this. The goal of this is to remove the warnings, and wanted to see if there were concerns going down this route.

**Comment by pquentin** [comment]
@badcure Thank you for putting this pull request together! It's easy to read, and the change does make sense.

However, I don't know enough about header parsing to reason about possble issues (eg. security) so I'm not going to merge this myself, sorry. :(

**Comment by harryhobson** [comment]
Hi, who is the right person to review and accept this pull request? It has been sitting dormant for a while so I just want to check this hasn't been forgotten/assigned.

**Comment by pquentin** [comment]
@sethmlarson Any ideas?

**Comment by sethmlarson** [comment]
Sorry that this took so long, I've done the following:
- Reviewed the change, I believe that this is a good change for us :+1:
- Confirmed that totally valid HTTP multipart/mixed responses receive these defects (even when using raw httplib) so we definitely should be ignoring them if we're only parsing headers.
- Added a test case that asserts that the `log.warning()` isn't called when receiving a multipart/mixed message
- Made some changes to the PR to remove the unnecessary `pytest.mark.parametrize()` and use `onlyPy3`

**Review by hodbn — DISMISSED** [review]

**Pull request merged**
