### PR TITLE
Travis CI: The sudo: tag is fully deprecated

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by pquentin** [comment]
True! For what it's worth we also have a few other warnings:

```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: unknown key stage (test)
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs
```

**Comment by cclauss** [comment]
How did you get those?

**Comment by pquentin** [comment]
I recently closed/reopened the Travis configuration of my urllib3 fork, which got me a travis-ci.com account, not a travis-ci.org one. And then the information can be seen under View Config -> Build config validation: https://travis-ci.com/pquentin/urllib3/builds/145416240/config

That does not prevent merging your pull request, I was just sharing

**Comment by pquentin** [comment]
Thanks! This fixes all warnings as can be seen in https://travis-ci.com/pquentin/urllib3/builds/145706678/config

**Pull request merged**
