### PR TITLE
Test and document support for the Python 3.7 release

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks @jdufresne! Could you please close your PR and open it again to see if the failures are the same? This will make sure that we can still see the failures in the future. For reference, the failed Python 3.7 build is https://travis-ci.org/urllib3/urllib3/jobs/403360745.

**Comment by jdufresne** [comment]
Just reran Travis, same issue. Python 3.7 is still failing. This will require a bit of investigation.

**Comment by pquentin** [comment]
Now that #1475 was merged, I guess we can now revisit this PR to test 3.7 instead of 3.7-dev.

**Comment by jdufresne** [comment]
I have rebased. Jenkins is now green.

**Comment by SethMichaelLarson** [comment]
Thanks @jdufresne!

**Pull request merged**
