### PR TITLE
Expose peer certificate

### PR DESCRIPTION
**Pull request by jschlyter**
In order to do more advanced fingerprinting on certificates, it would be most useful if the peer certificate could be exposed in the connection and in responses.

If possible, I'd like to expose the entire peer certificate chain for things like DANE/TLSA validation, but I'm not sure where do find this information.

### CODE REVIEW

**Comment by jschlyter** [comment]
Perhaps @sethmlarson can provide some guidance on where to find the entire peer certificate chain?

**Comment by pquentin** [comment]
We can't get the entire peer certificate chain because it's not possible in the standard library, see https://bugs.python.org/issue18233. And we probably don't want to allow this in the PyOpenSSL and SecureTransport contrib backends if it's not possible with the standard library?

**Comment by jschlyter** [comment]
> We can't get the entire peer certificate chain because it's not possible in the standard library, see https://bugs.python.org/issue18233. And we probably don't want to allow this in the PyOpenSSL and SecureTransport contrib backends if it's not possible with the standard library?

I agree that certificate chain support be added later once/if support by the standard library.

**Comment by sethmlarson** [comment]
This might be a good use-case for sub-classing `HTTPConnection` and adding this additional step to `connect()`.  The library allows subclassing and using your custom class in a pool via `ConnectionPool.ConnectionCls`.

**Comment by sethmlarson** [comment]
Going to close this PR per above comment.

**Comment by jschlyter** [comment]
Perhaps now possible as described in https://github.com/urllib3/urllib3/issues/2438

**Pull request closed without merging**
