### PR TITLE
[1.26] Configure CPython 3.12 in CI

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]

**Comment by illia-v** [comment]
I canceled the CI workflow because some jobs hasn't finished in 2 hours

**Review by skydiver1980 — APPROVED** [review]

**Review by skydiver1980 — APPROVED** [review]

**Comment by pquentin** [comment]
Or when Python 3.13 alpha 2 is out: https://github.com/python/cpython/issues/112026#issuecomment-1813191948

**Comment by illia-v** [comment]
@pquentin I wanted to post the comment in #3156 😄

The latest CI run there used 3.13.0a2, but it failed without the CFFI patch https://github.com/urllib3/urllib3/actions/runs/6872478062/job/18998233027?pr=3156

**Comment by pquentin** [comment]
Done in https://github.com/urllib3/urllib3/pull/3436, closing. Thanks @illia-v!

**Pull request closed without merging**
