### PR TITLE
Fix ssl_version tests

### PR DESCRIPTION
**Pull request by ecerulm**
The current test setup gives some errors when `ssl.HAS_TLSv1.3`, since 
there is no corresponding `ssl.PROTOCOL_TLSv1.3`. 

I modified the test suite to use `ssl.PROTOCOL_TLS_CLIENT` when `TLSv1.3`, and skipping the following case when testing the TLSv1.3 case
* `test_ssl_version_is_deprecated`
* `test_ssl_context_ssl_version_uses_ssl_min_max_versions `

### CODE REVIEW

**Comment by ecerulm** [comment]
@pquentin , I look into the failures in #3335 

I think this solves them. Not sure why this failures got unveiled by the pytest 7.4.0 to pytest 8.0.0 upgrade. 

But

**Review by sethmlarson — DISMISSED** [review]
LGTM, thank you!

**Comment by pquentin** [comment]
This appears to break `test_get_all_memory_usage_single_chunk` on macOS 3.10/11/12 somehow:

```pytest
_________ TestBytesQueueBuffer.test_get_all_memory_usage_single_chunk __________
Test was limited to 10.0MiB but allocated 10.1MiB
------------------------------ memray-max-memory -------------------------------
List of allocations:
    - 64.0KiB allocated here:
        read:/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/ssl.py:1165
        ...
    - 64.0KiB allocated here:
        read:/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/ssl.py:1165
        ...
    - 10.0MiB allocated here:
        test_get_all_memory_usage_single_chunk:/Users/runner/work/urllib3/urllib3/test/test_response.py:115
        ...
```

```pytest
_________ TestBytesQueueBuffer.test_get_all_memory_usage_single_chunk __________
Test was limited to 10.0MiB but allocated 10.1MiB
------------------------------ memray-max-memory -------------------------------
List of allocations:
    - 64.0KiB allocated here:
        read:/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py:1169
        ...
    - 628.0B allocated here:
        wrapper:/Users/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pytest_memray/plugin.py:191
    - 528.0B allocated here:
        __init__:/Users/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/urllib3/response.py:246
        ...
    - 10.0MiB allocated here:
        test_get_all_memory_usage_single_chunk:/Users/runner/work/urllib3/urllib3/test/test_response.py:115
        ...
```

```pytest
 _________ TestBytesQueueBuffer.test_get_all_memory_usage_single_chunk __________
Test was limited to 10.0MiB but allocated 10.1MiB
------------------------------ memray-max-memory -------------------------------
List of allocations:
    - 64.0KiB allocated here:
        read:/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py:1107
        ...
    - 528.0B allocated here:
        __init__:/Users/runner/work/urllib3/urllib3/.nox/test-3-12/lib/python3.12/site-packages/urllib3/response.py:246
        ...
    - 10.0MiB allocated here:
        test_get_all_memory_usage_single_chunk:/Users/runner/work/urllib3/urllib3/test/test_response.py:115
        ...
```

The 528B in response.py at line 246 are allocated by the deque. The 64KiB are allocated in `SSLSocket.read()` but this makes no sense in this context as the test does not call SSL at all:

https://github.com/urllib3/urllib3/blob/23f2287eb526d9384dddeedb6f6345e263bb9b86/test/test_response.py#L112-L117

This sounds like an incompatibility between pytest 8 and pytest-memray on macOS that we should report to pytest-memray.

**Comment by pquentin** [comment]
That said, we can merge this pull request while staying on pytest 7.

**Comment by ecerulm** [comment]
I wonder , **should we increase the memory limit for this test to "10.064 MB"?** After all we already have "10.01 MB" which I assume the "0.01" was to give some room as indicated in [pytest.mark.limit_memory](https://pytest-memray.readthedocs.io/en/latest/usage.html#pytest.mark.limit_memory)


`test/test_response.py::TestBytesQueueBuffer::test_get_all_memory_usage_single_chunk` fails  not only on macOS 

* macOS 3.10
* macOS 3.11
* macOS 3.12
* Ubuntu 22.04 3.12 
* Ubuntu 3.x test_brotlipy


I investigated a bit 
* if we run `test/test_response.py::TestBytesQueueBuffer` test alone they will pass 
* if we run `test/contrib/test_pyopenssl.py::TestSocketClosing:test_socket_close_socket_then_file`  or `test/contrib/test_pyopenssl.py::TestSocketClosing::test_socket_close_stays_open_with_makefile_open`  before `test/test_response.py::TestBytesQueueBuffer::test_get_all_memory_usage_single_chunk` then it will fail. 
   * I can reproduce 100% on my mac laptop.  
   * failure seem to be a **consequence of running other tests prior to this one**. 


```
.nox/test-3-12/bin/python -m pytest --memray -v -ra --color=auto --tb=native --durations=10 --strict-config --strict-markers test/contrib/test_pyopenssl.py::TestSocketClosing::test_socket_close_socket_then_file test/test_response.py::TestBytesQueueBuffer::test_get_all_memory_usage_single_chunk
==================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________ TestBytesQueueBuffer.test_get_all_memory_usage_single_chunk ___________________________________________________________________________
Test was limited to 10.0MiB but allocated 10.1MiB
------------------------------------------------------------------------------------------------ memray-max-memory ------------------------------------------------------------------------------------------------
List of allocations:
    - 64.0KiB allocated here:
        read:/usr/local/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py:1107
        ...
    - 10.0MiB allocated here:
        test_get_all_memory_usage_single_chunk:/Users/rubelagu/git/urllib3/test/test_response.py:115
        ...
    - 528.0B allocated here:
        __init__:/Users/rubelagu/git/urllib3/.nox/test-3-12/lib/python3.12/site-packages/urllib3/response.py:246
        ...



.nox/test-3-12/bin/python -m pytest --memray -v -ra --color=auto --tb=native --durations=10 --strict-config --strict-markers test/contrib/test_pyopenssl.py::TestSocketClosing::test_socket_close_stays_open_with_makefile_open test/test_response.py::TestBytesQueueBuffer::test_get_all_memory_usage_single_chunk
==================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________ TestBytesQueueBuffer.test_get_all_memory_usage_single_chunk ___________________________________________________________________________
Test was limited to 10.0MiB but allocated 10.1MiB
------------------------------------------------------------------------------------------------ memray-max-memory ------------------------------------------------------------------------------------------------
List of allocations:
    - 64.0KiB allocated here:
        read:/usr/local/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py:1107
        ...
    - 528.0B allocated here:
        __init__:/Users/rubelagu/git/urllib3/.nox/test-3-12/lib/python3.12/site-packages/urllib3/response.py:246
        ...
    - 10.0MiB allocated here:
        test_get_all_memory_usage_single_chunk:/Users/rubelagu/git/urllib3/test/test_response.py:115

```

**Review by sethmlarson — APPROVED** [review]
Awesome, thanks @ecerulm! This'll make our transition to pytest 8 smoother later :)

**Pull request merged**
