### PR TITLE
Add 1.26.16 release to CHANGES.rst on main

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Review by pquentin — COMMENTED** [review]
Should we remove the entry from the 2.0.0 changelog then?

**Comment by illia-v** [comment]
> Should we remove the entry from the 2.0.0 changelog then?

I'd apply a rule that for a release we should list changes from the closest lower version released on a date before the new release's date 🤔
So, in this case I wouldn't remove the entry.

**Comment by pquentin** [comment]
So you're saying we should list it twice? That works for me

**Comment by illia-v** [comment]
> So you're saying we should list it twice? That works for me

Yes, I'd list them twice 🙂

**Review by illia-v — APPROVED** [review]

**Pull request merged**
