### PR TITLE
Update links to point to organization

### PR DESCRIPTION
**Pull request by SethMichaelLarson**

### CODE REVIEW

**Comment by jonparrott** [comment]
lol I was just working on this.

**Comment by SethMichaelLarson** [comment]
Mind meld!

**Comment by jonparrott** [comment]
Restarting builds to see if appveyor is awake yet

**Comment by jonparrott** [comment]
lol github has rate-limited my account. Cool. Appveyor won't run. for now. ;)

**Comment by SethMichaelLarson** [comment]
Would you like me to give it a quick open-close? I'm not sure how it determines which set of OAuth credentials to use. :P

**Comment by jonparrott** [comment]
AppVeyor is exceedingly silly and authenticates as the user who set up the project.

**Comment by jonparrott** [comment]
Merging despite flaky macos tests. (Can we do anything about that?)

**Pull request merged**
