### PR TITLE
Switch to Nox

### PR DESCRIPTION
**Pull request by theacodes**

### CODE REVIEW

**Comment by theacodes** [comment]
No need to review yet, as I'm sure that travis is about to positively explode.

**Comment by theacodes** [comment]
Okay, @sethmlarson, this is ready for your consideration.

**Comment by theacodes** [comment]
Closes #1576 as well.

**Comment by pquentin** [comment]
This pull request decreased coverage from 99.89% to 98.43% because codecov no longer receives the builds from Travis, only the AppVeyor ones. Latest example: https://codecov.io/gh/urllib3/urllib3/commit/49eea8082ab34094d0c53f1d26e5c588d5372d74/build

**Comment by sethmlarson** [comment]
Nice catch @pquentin!

**Comment by pquentin** [comment]
Is it possible to add the codecov checks to GitHub (codecov/project and codecov/patch)? I think this would allow https://github.com/urllib3/urllib3/blob/master/codecov.yml to take effect.

See https://github.com/python-trio/trio/pull/1029 for an example. When clicking on "Show all checks", I see this:

codecov checks on GitHub

**Pull request merged**
